// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Serverless.Fluent;
using Elastic.Clients.Elasticsearch.Serverless.Next;
using Elastic.Clients.Elasticsearch.Serverless.Serialization;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Elastic.Clients.Elasticsearch.Serverless.Security;

internal sealed partial class QueryRoleConverter : System.Text.Json.Serialization.JsonConverter<QueryRole>
{
	private static readonly System.Text.Json.JsonEncodedText PropApplications = System.Text.Json.JsonEncodedText.Encode("applications");
	private static readonly System.Text.Json.JsonEncodedText PropCluster = System.Text.Json.JsonEncodedText.Encode("cluster");
	private static readonly System.Text.Json.JsonEncodedText PropDescription = System.Text.Json.JsonEncodedText.Encode("description");
	private static readonly System.Text.Json.JsonEncodedText PropIndices = System.Text.Json.JsonEncodedText.Encode("indices");
	private static readonly System.Text.Json.JsonEncodedText PropIndices1 = System.Text.Json.JsonEncodedText.Encode("index");
	private static readonly System.Text.Json.JsonEncodedText PropMetadata = System.Text.Json.JsonEncodedText.Encode("metadata");
	private static readonly System.Text.Json.JsonEncodedText PropName = System.Text.Json.JsonEncodedText.Encode("name");
	private static readonly System.Text.Json.JsonEncodedText PropRestriction = System.Text.Json.JsonEncodedText.Encode("restriction");
	private static readonly System.Text.Json.JsonEncodedText PropRunAs = System.Text.Json.JsonEncodedText.Encode("run_as");
	private static readonly System.Text.Json.JsonEncodedText PropSort = System.Text.Json.JsonEncodedText.Encode("_sort");
	private static readonly System.Text.Json.JsonEncodedText PropTransientMetadata = System.Text.Json.JsonEncodedText.Encode("transient_metadata");

	public override QueryRole Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
	{
		reader.ValidateToken(System.Text.Json.JsonTokenType.StartObject);
		LocalJsonProperty<IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.ApplicationPrivileges>?> propApplications = default;
		LocalJsonProperty<IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.ClusterPrivilege>?> propCluster = default;
		LocalJsonProperty<string?> propDescription = default;
		LocalJsonProperty<IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.IndicesPrivileges>?> propIndices = default;
		LocalJsonProperty<IReadOnlyDictionary<string, object>?> propMetadata = default;
		LocalJsonProperty<string> propName = default;
		LocalJsonProperty<Elastic.Clients.Elasticsearch.Serverless.Security.Restriction?> propRestriction = default;
		LocalJsonProperty<IReadOnlyCollection<string>?> propRunAs = default;
		LocalJsonProperty<IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.FieldValue>?> propSort = default;
		LocalJsonProperty<IReadOnlyDictionary<string, object>?> propTransientMetadata = default;
		while (reader.Read() && reader.TokenType is System.Text.Json.JsonTokenType.PropertyName)
		{
			if (propApplications.TryRead(ref reader, options, PropApplications))
			{
				continue;
			}

			if (propCluster.TryRead(ref reader, options, PropCluster))
			{
				continue;
			}

			if (propDescription.TryRead(ref reader, options, PropDescription))
			{
				continue;
			}

			if (propIndices.TryRead(ref reader, options, PropIndices) || propIndices.TryRead(ref reader, options, PropIndices1))
			{
				continue;
			}

			if (propMetadata.TryRead(ref reader, options, PropMetadata))
			{
				continue;
			}

			if (propName.TryRead(ref reader, options, PropName))
			{
				continue;
			}

			if (propRestriction.TryRead(ref reader, options, PropRestriction))
			{
				continue;
			}

			if (propRunAs.TryRead(ref reader, options, PropRunAs))
			{
				continue;
			}

			if (propSort.TryRead(ref reader, options, PropSort))
			{
				continue;
			}

			if (propTransientMetadata.TryRead(ref reader, options, PropTransientMetadata))
			{
				continue;
			}

			throw new System.Text.Json.JsonException($"Unknown JSON property '{reader.GetString()}' for type '{typeToConvert.Name}'.");
		}

		reader.ValidateToken(System.Text.Json.JsonTokenType.EndObject);
		return new QueryRole
		{
			Applications = propApplications.Value
,
			Cluster = propCluster.Value
,
			Description = propDescription.Value
,
			Indices = propIndices.Value
,
			Metadata = propMetadata.Value
,
			Name = propName.Value
,
			Restriction = propRestriction.Value
,
			RunAs = propRunAs.Value
,
			Sort = propSort.Value
,
			TransientMetadata = propTransientMetadata.Value
		};
	}

	public override void Write(System.Text.Json.Utf8JsonWriter writer, QueryRole value, System.Text.Json.JsonSerializerOptions options)
	{
		writer.WriteStartObject();
		writer.WriteProperty(options, PropApplications, value.Applications);
		writer.WriteProperty(options, PropCluster, value.Cluster);
		writer.WriteProperty(options, PropDescription, value.Description);
		writer.WriteProperty(options, PropIndices, value.Indices);
		writer.WriteProperty(options, PropMetadata, value.Metadata);
		writer.WriteProperty(options, PropName, value.Name);
		writer.WriteProperty(options, PropRestriction, value.Restriction);
		writer.WriteProperty(options, PropRunAs, value.RunAs);
		writer.WriteProperty(options, PropSort, value.Sort);
		writer.WriteProperty(options, PropTransientMetadata, value.TransientMetadata);
		writer.WriteEndObject();
	}
}

[JsonConverter(typeof(QueryRoleConverter))]
public sealed partial class QueryRole
{
	/// <summary>
	/// <para>
	/// A list of application privilege entries
	/// </para>
	/// </summary>
	public IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.ApplicationPrivileges>? Applications { get; init; }

	/// <summary>
	/// <para>
	/// A list of cluster privileges. These privileges define the cluster level actions that API keys are able to execute.
	/// </para>
	/// </summary>
	public IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.ClusterPrivilege>? Cluster { get; init; }

	/// <summary>
	/// <para>
	/// Optional description of the role descriptor
	/// </para>
	/// </summary>
	public string? Description { get; init; }

	/// <summary>
	/// <para>
	/// A list of indices permissions entries.
	/// </para>
	/// </summary>
	public IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.Security.IndicesPrivileges>? Indices { get; init; }

	/// <summary>
	/// <para>
	/// Optional meta-data. Within the metadata object, keys that begin with <c>_</c> are reserved for system usage.
	/// </para>
	/// </summary>
	public IReadOnlyDictionary<string, object>? Metadata { get; init; }

	/// <summary>
	/// <para>
	/// Name of the role.
	/// </para>
	/// </summary>
	public string Name { get; init; }

	/// <summary>
	/// <para>
	/// Restriction for when the role descriptor is allowed to be effective.
	/// </para>
	/// </summary>
	public Elastic.Clients.Elasticsearch.Serverless.Security.Restriction? Restriction { get; init; }

	/// <summary>
	/// <para>
	/// A list of users that the API keys can impersonate. <em>Note</em>: in Serverless, the run-as feature is disabled. For API compatibility, you can still specify an empty <c>run_as</c> field, but a non-empty list will be rejected.
	/// </para>
	/// </summary>
	public IReadOnlyCollection<string>? RunAs { get; init; }
	public IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.FieldValue>? Sort { get; init; }
	public IReadOnlyDictionary<string, object>? TransientMetadata { get; init; }
}