// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Serverless.Fluent;
using Elastic.Clients.Elasticsearch.Serverless.Requests;
using Elastic.Clients.Elasticsearch.Serverless.Serialization;
using Elastic.Transport;
using Elastic.Transport.Extensions;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Elastic.Clients.Elasticsearch.Serverless.Snapshot;

public sealed partial class RestoreRequestParameters : RequestParameters
{
	/// <summary>
	/// <para>
	/// The period to wait for the master node.
	/// If the master node is not available before the timeout expires, the request fails and returns an error.
	/// To indicate that the request should never timeout, set it to <c>-1</c>.
	/// </para>
	/// </summary>
	public Elastic.Clients.Elasticsearch.Serverless.Duration? MasterTimeout { get => Q<Elastic.Clients.Elasticsearch.Serverless.Duration?>("master_timeout"); set => Q("master_timeout", value); }

	/// <summary>
	/// <para>
	/// If <c>true</c>, the request returns a response when the restore operation completes.
	/// The operation is complete when it finishes all attempts to recover primary shards for restored indices.
	/// This applies even if one or more of the recovery attempts fail.
	/// </para>
	/// <para>
	/// If <c>false</c>, the request returns a response when the restore operation initializes.
	/// </para>
	/// </summary>
	public bool? WaitForCompletion { get => Q<bool?>("wait_for_completion"); set => Q("wait_for_completion", value); }
}

/// <summary>
/// <para>
/// Restore a snapshot.
/// Restore a snapshot of a cluster or data streams and indices.
/// </para>
/// <para>
/// You can restore a snapshot only to a running cluster with an elected master node.
/// The snapshot repository must be registered and available to the cluster.
/// The snapshot and cluster versions must be compatible.
/// </para>
/// <para>
/// To restore a snapshot, the cluster's global metadata must be writable. Ensure there are't any cluster blocks that prevent writes. The restore operation ignores index blocks.
/// </para>
/// <para>
/// Before you restore a data stream, ensure the cluster contains a matching index template with data streams enabled. To check, use the index management feature in Kibana or the get index template API:
/// </para>
/// <code>
/// GET _index_template/*?filter_path=index_templates.name,index_templates.index_template.index_patterns,index_templates.index_template.data_stream
/// </code>
/// <para>
/// If no such template exists, you can create one or restore a cluster state that contains one. Without a matching index template, a data stream can't roll over or create backing indices.
/// </para>
/// <para>
/// If your snapshot contains data from App Search or Workplace Search, you must restore the Enterprise Search encryption key before you restore the snapshot.
/// </para>
/// </summary>
public sealed partial class RestoreRequest : PlainRequest<RestoreRequestParameters>
{
	public RestoreRequest(Elastic.Clients.Elasticsearch.Serverless.Name repository, Elastic.Clients.Elasticsearch.Serverless.Name snapshot) : base(r => r.Required("repository", repository).Required("snapshot", snapshot))
	{
	}

	internal override ApiUrls ApiUrls => ApiUrlLookup.SnapshotRestore;

	protected override HttpMethod StaticHttpMethod => HttpMethod.POST;

	internal override bool SupportsBody => true;

	internal override string OperationName => "snapshot.restore";

	/// <summary>
	/// <para>
	/// The period to wait for the master node.
	/// If the master node is not available before the timeout expires, the request fails and returns an error.
	/// To indicate that the request should never timeout, set it to <c>-1</c>.
	/// </para>
	/// </summary>
	[JsonIgnore]
	public Elastic.Clients.Elasticsearch.Serverless.Duration? MasterTimeout { get => Q<Elastic.Clients.Elasticsearch.Serverless.Duration?>("master_timeout"); set => Q("master_timeout", value); }

	/// <summary>
	/// <para>
	/// If <c>true</c>, the request returns a response when the restore operation completes.
	/// The operation is complete when it finishes all attempts to recover primary shards for restored indices.
	/// This applies even if one or more of the recovery attempts fail.
	/// </para>
	/// <para>
	/// If <c>false</c>, the request returns a response when the restore operation initializes.
	/// </para>
	/// </summary>
	[JsonIgnore]
	public bool? WaitForCompletion { get => Q<bool?>("wait_for_completion"); set => Q("wait_for_completion", value); }

	/// <summary>
	/// <para>
	/// The feature states to restore.
	/// If <c>include_global_state</c> is <c>true</c>, the request restores all feature states in the snapshot by default.
	/// If <c>include_global_state</c> is <c>false</c>, the request restores no feature states by default.
	/// Note that specifying an empty array will result in the default behavior.
	/// To restore no feature states, regardless of the <c>include_global_state</c> value, specify an array containing only the value <c>none</c> (<c>["none"]</c>).
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("feature_states")]
	public ICollection<string>? FeatureStates { get; set; }

	/// <summary>
	/// <para>
	/// The index settings to not restore from the snapshot.
	/// You can't use this option to ignore <c>index.number_of_shards</c>.
	/// </para>
	/// <para>
	/// For data streams, this option applies only to restored backing indices.
	/// New backing indices are configured using the data stream's matching index template.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("ignore_index_settings")]
	public ICollection<string>? IgnoreIndexSettings { get; set; }

	/// <summary>
	/// <para>
	/// If <c>true</c>, the request ignores any index or data stream in indices that's missing from the snapshot.
	/// If <c>false</c>, the request returns an error for any missing index or data stream.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("ignore_unavailable")]
	public bool? IgnoreUnavailable { get; set; }

	/// <summary>
	/// <para>
	/// If <c>true</c>, the request restores aliases for any restored data streams and indices.
	/// If <c>false</c>, the request doesn’t restore aliases.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("include_aliases")]
	public bool? IncludeAliases { get; set; }

	/// <summary>
	/// <para>
	/// If <c>true</c>, restore the cluster state. The cluster state includes:
	/// </para>
	/// <list type="bullet">
	/// <item>
	/// <para>
	/// Persistent cluster settings
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Index templates
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Legacy index templates
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Ingest pipelines
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Index lifecycle management (ILM) policies
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Stored scripts
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// For snapshots taken after 7.12.0, feature states
	/// </para>
	/// </item>
	/// </list>
	/// <para>
	/// If <c>include_global_state</c> is <c>true</c>, the restore operation merges the legacy index templates in your cluster with the templates contained in the snapshot, replacing any existing ones whose name matches one in the snapshot.
	/// It completely removes all persistent settings, non-legacy index templates, ingest pipelines, and ILM lifecycle policies that exist in your cluster and replaces them with the corresponding items from the snapshot.
	/// </para>
	/// <para>
	/// Use the <c>feature_states</c> parameter to configure how feature states are restored.
	/// </para>
	/// <para>
	/// If <c>include_global_state</c> is <c>true</c> and a snapshot was created without a global state then the restore request will fail.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("include_global_state")]
	public bool? IncludeGlobalState { get; set; }

	/// <summary>
	/// <para>
	/// Index settings to add or change in restored indices, including backing indices.
	/// You can't use this option to change <c>index.number_of_shards</c>.
	/// </para>
	/// <para>
	/// For data streams, this option applies only to restored backing indices.
	/// New backing indices are configured using the data stream's matching index template.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("index_settings")]
	public Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettings? IndexSettings { get; set; }

	/// <summary>
	/// <para>
	/// A comma-separated list of indices and data streams to restore.
	/// It supports a multi-target syntax.
	/// The default behavior is all regular indices and regular data streams in the snapshot.
	/// </para>
	/// <para>
	/// You can't use this parameter to restore system indices or system data streams.
	/// Use <c>feature_states</c> instead.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("indices")]
	public Elastic.Clients.Elasticsearch.Serverless.Indices? Indices { get; set; }

	/// <summary>
	/// <para>
	/// If <c>false</c>, the entire restore operation will fail if one or more indices included in the snapshot do not have all primary shards available.
	/// </para>
	/// <para>
	/// If true, it allows restoring a partial snapshot of indices with unavailable shards.
	/// Only shards that were successfully included in the snapshot will be restored.
	/// All missing shards will be recreated as empty.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("partial")]
	public bool? Partial { get; set; }

	/// <summary>
	/// <para>
	/// A rename pattern to apply to restored data streams and indices.
	/// Data streams and indices matching the rename pattern will be renamed according to <c>rename_replacement</c>.
	/// </para>
	/// <para>
	/// The rename pattern is applied as defined by the regular expression that supports referencing the original text, according to the <c>appendReplacement</c> logic.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("rename_pattern")]
	public string? RenamePattern { get; set; }

	/// <summary>
	/// <para>
	/// The rename replacement string that is used with the <c>rename_pattern</c>.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("rename_replacement")]
	public string? RenameReplacement { get; set; }
}

/// <summary>
/// <para>
/// Restore a snapshot.
/// Restore a snapshot of a cluster or data streams and indices.
/// </para>
/// <para>
/// You can restore a snapshot only to a running cluster with an elected master node.
/// The snapshot repository must be registered and available to the cluster.
/// The snapshot and cluster versions must be compatible.
/// </para>
/// <para>
/// To restore a snapshot, the cluster's global metadata must be writable. Ensure there are't any cluster blocks that prevent writes. The restore operation ignores index blocks.
/// </para>
/// <para>
/// Before you restore a data stream, ensure the cluster contains a matching index template with data streams enabled. To check, use the index management feature in Kibana or the get index template API:
/// </para>
/// <code>
/// GET _index_template/*?filter_path=index_templates.name,index_templates.index_template.index_patterns,index_templates.index_template.data_stream
/// </code>
/// <para>
/// If no such template exists, you can create one or restore a cluster state that contains one. Without a matching index template, a data stream can't roll over or create backing indices.
/// </para>
/// <para>
/// If your snapshot contains data from App Search or Workplace Search, you must restore the Enterprise Search encryption key before you restore the snapshot.
/// </para>
/// </summary>
public sealed partial class RestoreRequestDescriptor<TDocument> : RequestDescriptor<RestoreRequestDescriptor<TDocument>, RestoreRequestParameters>
{
	internal RestoreRequestDescriptor(Action<RestoreRequestDescriptor<TDocument>> configure) => configure.Invoke(this);

	public RestoreRequestDescriptor(Elastic.Clients.Elasticsearch.Serverless.Name repository, Elastic.Clients.Elasticsearch.Serverless.Name snapshot) : base(r => r.Required("repository", repository).Required("snapshot", snapshot))
	{
	}

	internal override ApiUrls ApiUrls => ApiUrlLookup.SnapshotRestore;

	protected override HttpMethod StaticHttpMethod => HttpMethod.POST;

	internal override bool SupportsBody => true;

	internal override string OperationName => "snapshot.restore";

	public RestoreRequestDescriptor<TDocument> MasterTimeout(Elastic.Clients.Elasticsearch.Serverless.Duration? masterTimeout) => Qs("master_timeout", masterTimeout);
	public RestoreRequestDescriptor<TDocument> WaitForCompletion(bool? waitForCompletion = true) => Qs("wait_for_completion", waitForCompletion);

	public RestoreRequestDescriptor<TDocument> Repository(Elastic.Clients.Elasticsearch.Serverless.Name repository)
	{
		RouteValues.Required("repository", repository);
		return Self;
	}

	public RestoreRequestDescriptor<TDocument> Snapshot(Elastic.Clients.Elasticsearch.Serverless.Name snapshot)
	{
		RouteValues.Required("snapshot", snapshot);
		return Self;
	}

	private ICollection<string>? FeatureStatesValue { get; set; }
	private ICollection<string>? IgnoreIndexSettingsValue { get; set; }
	private bool? IgnoreUnavailableValue { get; set; }
	private bool? IncludeAliasesValue { get; set; }
	private bool? IncludeGlobalStateValue { get; set; }
	private Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettings? IndexSettingsValue { get; set; }
	private Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettingsDescriptor<TDocument> IndexSettingsDescriptor { get; set; }
	private Action<Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettingsDescriptor<TDocument>> IndexSettingsDescriptorAction { get; set; }
	private Elastic.Clients.Elasticsearch.Serverless.Indices? IndicesValue { get; set; }
	private bool? PartialValue { get; set; }
	private string? RenamePatternValue { get; set; }
	private string? RenameReplacementValue { get; set; }

	/// <summary>
	/// <para>
	/// The feature states to restore.
	/// If <c>include_global_state</c> is <c>true</c>, the request restores all feature states in the snapshot by default.
	/// If <c>include_global_state</c> is <c>false</c>, the request restores no feature states by default.
	/// Note that specifying an empty array will result in the default behavior.
	/// To restore no feature states, regardless of the <c>include_global_state</c> value, specify an array containing only the value <c>none</c> (<c>["none"]</c>).
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor<TDocument> FeatureStates(ICollection<string>? featureStates)
	{
		FeatureStatesValue = featureStates;
		return Self;
	}

	/// <summary>
	/// <para>
	/// The index settings to not restore from the snapshot.
	/// You can't use this option to ignore <c>index.number_of_shards</c>.
	/// </para>
	/// <para>
	/// For data streams, this option applies only to restored backing indices.
	/// New backing indices are configured using the data stream's matching index template.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor<TDocument> IgnoreIndexSettings(ICollection<string>? ignoreIndexSettings)
	{
		IgnoreIndexSettingsValue = ignoreIndexSettings;
		return Self;
	}

	/// <summary>
	/// <para>
	/// If <c>true</c>, the request ignores any index or data stream in indices that's missing from the snapshot.
	/// If <c>false</c>, the request returns an error for any missing index or data stream.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor<TDocument> IgnoreUnavailable(bool? ignoreUnavailable = true)
	{
		IgnoreUnavailableValue = ignoreUnavailable;
		return Self;
	}

	/// <summary>
	/// <para>
	/// If <c>true</c>, the request restores aliases for any restored data streams and indices.
	/// If <c>false</c>, the request doesn’t restore aliases.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor<TDocument> IncludeAliases(bool? includeAliases = true)
	{
		IncludeAliasesValue = includeAliases;
		return Self;
	}

	/// <summary>
	/// <para>
	/// If <c>true</c>, restore the cluster state. The cluster state includes:
	/// </para>
	/// <list type="bullet">
	/// <item>
	/// <para>
	/// Persistent cluster settings
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Index templates
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Legacy index templates
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Ingest pipelines
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Index lifecycle management (ILM) policies
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Stored scripts
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// For snapshots taken after 7.12.0, feature states
	/// </para>
	/// </item>
	/// </list>
	/// <para>
	/// If <c>include_global_state</c> is <c>true</c>, the restore operation merges the legacy index templates in your cluster with the templates contained in the snapshot, replacing any existing ones whose name matches one in the snapshot.
	/// It completely removes all persistent settings, non-legacy index templates, ingest pipelines, and ILM lifecycle policies that exist in your cluster and replaces them with the corresponding items from the snapshot.
	/// </para>
	/// <para>
	/// Use the <c>feature_states</c> parameter to configure how feature states are restored.
	/// </para>
	/// <para>
	/// If <c>include_global_state</c> is <c>true</c> and a snapshot was created without a global state then the restore request will fail.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor<TDocument> IncludeGlobalState(bool? includeGlobalState = true)
	{
		IncludeGlobalStateValue = includeGlobalState;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Index settings to add or change in restored indices, including backing indices.
	/// You can't use this option to change <c>index.number_of_shards</c>.
	/// </para>
	/// <para>
	/// For data streams, this option applies only to restored backing indices.
	/// New backing indices are configured using the data stream's matching index template.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor<TDocument> IndexSettings(Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettings? indexSettings)
	{
		IndexSettingsDescriptor = null;
		IndexSettingsDescriptorAction = null;
		IndexSettingsValue = indexSettings;
		return Self;
	}

	public RestoreRequestDescriptor<TDocument> IndexSettings(Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettingsDescriptor<TDocument> descriptor)
	{
		IndexSettingsValue = null;
		IndexSettingsDescriptorAction = null;
		IndexSettingsDescriptor = descriptor;
		return Self;
	}

	public RestoreRequestDescriptor<TDocument> IndexSettings(Action<Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettingsDescriptor<TDocument>> configure)
	{
		IndexSettingsValue = null;
		IndexSettingsDescriptor = null;
		IndexSettingsDescriptorAction = configure;
		return Self;
	}

	/// <summary>
	/// <para>
	/// A comma-separated list of indices and data streams to restore.
	/// It supports a multi-target syntax.
	/// The default behavior is all regular indices and regular data streams in the snapshot.
	/// </para>
	/// <para>
	/// You can't use this parameter to restore system indices or system data streams.
	/// Use <c>feature_states</c> instead.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor<TDocument> Indices(Elastic.Clients.Elasticsearch.Serverless.Indices? indices)
	{
		IndicesValue = indices;
		return Self;
	}

	/// <summary>
	/// <para>
	/// If <c>false</c>, the entire restore operation will fail if one or more indices included in the snapshot do not have all primary shards available.
	/// </para>
	/// <para>
	/// If true, it allows restoring a partial snapshot of indices with unavailable shards.
	/// Only shards that were successfully included in the snapshot will be restored.
	/// All missing shards will be recreated as empty.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor<TDocument> Partial(bool? partial = true)
	{
		PartialValue = partial;
		return Self;
	}

	/// <summary>
	/// <para>
	/// A rename pattern to apply to restored data streams and indices.
	/// Data streams and indices matching the rename pattern will be renamed according to <c>rename_replacement</c>.
	/// </para>
	/// <para>
	/// The rename pattern is applied as defined by the regular expression that supports referencing the original text, according to the <c>appendReplacement</c> logic.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor<TDocument> RenamePattern(string? renamePattern)
	{
		RenamePatternValue = renamePattern;
		return Self;
	}

	/// <summary>
	/// <para>
	/// The rename replacement string that is used with the <c>rename_pattern</c>.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor<TDocument> RenameReplacement(string? renameReplacement)
	{
		RenameReplacementValue = renameReplacement;
		return Self;
	}

	protected override void Serialize(Utf8JsonWriter writer, JsonSerializerOptions options, IElasticsearchClientSettings settings)
	{
		writer.WriteStartObject();
		if (FeatureStatesValue is not null)
		{
			writer.WritePropertyName("feature_states");
			JsonSerializer.Serialize(writer, FeatureStatesValue, options);
		}

		if (IgnoreIndexSettingsValue is not null)
		{
			writer.WritePropertyName("ignore_index_settings");
			JsonSerializer.Serialize(writer, IgnoreIndexSettingsValue, options);
		}

		if (IgnoreUnavailableValue.HasValue)
		{
			writer.WritePropertyName("ignore_unavailable");
			writer.WriteBooleanValue(IgnoreUnavailableValue.Value);
		}

		if (IncludeAliasesValue.HasValue)
		{
			writer.WritePropertyName("include_aliases");
			writer.WriteBooleanValue(IncludeAliasesValue.Value);
		}

		if (IncludeGlobalStateValue.HasValue)
		{
			writer.WritePropertyName("include_global_state");
			writer.WriteBooleanValue(IncludeGlobalStateValue.Value);
		}

		if (IndexSettingsDescriptor is not null)
		{
			writer.WritePropertyName("index_settings");
			JsonSerializer.Serialize(writer, IndexSettingsDescriptor, options);
		}
		else if (IndexSettingsDescriptorAction is not null)
		{
			writer.WritePropertyName("index_settings");
			JsonSerializer.Serialize(writer, new Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettingsDescriptor<TDocument>(IndexSettingsDescriptorAction), options);
		}
		else if (IndexSettingsValue is not null)
		{
			writer.WritePropertyName("index_settings");
			JsonSerializer.Serialize(writer, IndexSettingsValue, options);
		}

		if (IndicesValue is not null)
		{
			writer.WritePropertyName("indices");
			JsonSerializer.Serialize(writer, IndicesValue, options);
		}

		if (PartialValue.HasValue)
		{
			writer.WritePropertyName("partial");
			writer.WriteBooleanValue(PartialValue.Value);
		}

		if (!string.IsNullOrEmpty(RenamePatternValue))
		{
			writer.WritePropertyName("rename_pattern");
			writer.WriteStringValue(RenamePatternValue);
		}

		if (!string.IsNullOrEmpty(RenameReplacementValue))
		{
			writer.WritePropertyName("rename_replacement");
			writer.WriteStringValue(RenameReplacementValue);
		}

		writer.WriteEndObject();
	}
}

/// <summary>
/// <para>
/// Restore a snapshot.
/// Restore a snapshot of a cluster or data streams and indices.
/// </para>
/// <para>
/// You can restore a snapshot only to a running cluster with an elected master node.
/// The snapshot repository must be registered and available to the cluster.
/// The snapshot and cluster versions must be compatible.
/// </para>
/// <para>
/// To restore a snapshot, the cluster's global metadata must be writable. Ensure there are't any cluster blocks that prevent writes. The restore operation ignores index blocks.
/// </para>
/// <para>
/// Before you restore a data stream, ensure the cluster contains a matching index template with data streams enabled. To check, use the index management feature in Kibana or the get index template API:
/// </para>
/// <code>
/// GET _index_template/*?filter_path=index_templates.name,index_templates.index_template.index_patterns,index_templates.index_template.data_stream
/// </code>
/// <para>
/// If no such template exists, you can create one or restore a cluster state that contains one. Without a matching index template, a data stream can't roll over or create backing indices.
/// </para>
/// <para>
/// If your snapshot contains data from App Search or Workplace Search, you must restore the Enterprise Search encryption key before you restore the snapshot.
/// </para>
/// </summary>
public sealed partial class RestoreRequestDescriptor : RequestDescriptor<RestoreRequestDescriptor, RestoreRequestParameters>
{
	internal RestoreRequestDescriptor(Action<RestoreRequestDescriptor> configure) => configure.Invoke(this);

	public RestoreRequestDescriptor(Elastic.Clients.Elasticsearch.Serverless.Name repository, Elastic.Clients.Elasticsearch.Serverless.Name snapshot) : base(r => r.Required("repository", repository).Required("snapshot", snapshot))
	{
	}

	internal override ApiUrls ApiUrls => ApiUrlLookup.SnapshotRestore;

	protected override HttpMethod StaticHttpMethod => HttpMethod.POST;

	internal override bool SupportsBody => true;

	internal override string OperationName => "snapshot.restore";

	public RestoreRequestDescriptor MasterTimeout(Elastic.Clients.Elasticsearch.Serverless.Duration? masterTimeout) => Qs("master_timeout", masterTimeout);
	public RestoreRequestDescriptor WaitForCompletion(bool? waitForCompletion = true) => Qs("wait_for_completion", waitForCompletion);

	public RestoreRequestDescriptor Repository(Elastic.Clients.Elasticsearch.Serverless.Name repository)
	{
		RouteValues.Required("repository", repository);
		return Self;
	}

	public RestoreRequestDescriptor Snapshot(Elastic.Clients.Elasticsearch.Serverless.Name snapshot)
	{
		RouteValues.Required("snapshot", snapshot);
		return Self;
	}

	private ICollection<string>? FeatureStatesValue { get; set; }
	private ICollection<string>? IgnoreIndexSettingsValue { get; set; }
	private bool? IgnoreUnavailableValue { get; set; }
	private bool? IncludeAliasesValue { get; set; }
	private bool? IncludeGlobalStateValue { get; set; }
	private Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettings? IndexSettingsValue { get; set; }
	private Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettingsDescriptor IndexSettingsDescriptor { get; set; }
	private Action<Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettingsDescriptor> IndexSettingsDescriptorAction { get; set; }
	private Elastic.Clients.Elasticsearch.Serverless.Indices? IndicesValue { get; set; }
	private bool? PartialValue { get; set; }
	private string? RenamePatternValue { get; set; }
	private string? RenameReplacementValue { get; set; }

	/// <summary>
	/// <para>
	/// The feature states to restore.
	/// If <c>include_global_state</c> is <c>true</c>, the request restores all feature states in the snapshot by default.
	/// If <c>include_global_state</c> is <c>false</c>, the request restores no feature states by default.
	/// Note that specifying an empty array will result in the default behavior.
	/// To restore no feature states, regardless of the <c>include_global_state</c> value, specify an array containing only the value <c>none</c> (<c>["none"]</c>).
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor FeatureStates(ICollection<string>? featureStates)
	{
		FeatureStatesValue = featureStates;
		return Self;
	}

	/// <summary>
	/// <para>
	/// The index settings to not restore from the snapshot.
	/// You can't use this option to ignore <c>index.number_of_shards</c>.
	/// </para>
	/// <para>
	/// For data streams, this option applies only to restored backing indices.
	/// New backing indices are configured using the data stream's matching index template.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor IgnoreIndexSettings(ICollection<string>? ignoreIndexSettings)
	{
		IgnoreIndexSettingsValue = ignoreIndexSettings;
		return Self;
	}

	/// <summary>
	/// <para>
	/// If <c>true</c>, the request ignores any index or data stream in indices that's missing from the snapshot.
	/// If <c>false</c>, the request returns an error for any missing index or data stream.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor IgnoreUnavailable(bool? ignoreUnavailable = true)
	{
		IgnoreUnavailableValue = ignoreUnavailable;
		return Self;
	}

	/// <summary>
	/// <para>
	/// If <c>true</c>, the request restores aliases for any restored data streams and indices.
	/// If <c>false</c>, the request doesn’t restore aliases.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor IncludeAliases(bool? includeAliases = true)
	{
		IncludeAliasesValue = includeAliases;
		return Self;
	}

	/// <summary>
	/// <para>
	/// If <c>true</c>, restore the cluster state. The cluster state includes:
	/// </para>
	/// <list type="bullet">
	/// <item>
	/// <para>
	/// Persistent cluster settings
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Index templates
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Legacy index templates
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Ingest pipelines
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Index lifecycle management (ILM) policies
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// Stored scripts
	/// </para>
	/// </item>
	/// <item>
	/// <para>
	/// For snapshots taken after 7.12.0, feature states
	/// </para>
	/// </item>
	/// </list>
	/// <para>
	/// If <c>include_global_state</c> is <c>true</c>, the restore operation merges the legacy index templates in your cluster with the templates contained in the snapshot, replacing any existing ones whose name matches one in the snapshot.
	/// It completely removes all persistent settings, non-legacy index templates, ingest pipelines, and ILM lifecycle policies that exist in your cluster and replaces them with the corresponding items from the snapshot.
	/// </para>
	/// <para>
	/// Use the <c>feature_states</c> parameter to configure how feature states are restored.
	/// </para>
	/// <para>
	/// If <c>include_global_state</c> is <c>true</c> and a snapshot was created without a global state then the restore request will fail.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor IncludeGlobalState(bool? includeGlobalState = true)
	{
		IncludeGlobalStateValue = includeGlobalState;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Index settings to add or change in restored indices, including backing indices.
	/// You can't use this option to change <c>index.number_of_shards</c>.
	/// </para>
	/// <para>
	/// For data streams, this option applies only to restored backing indices.
	/// New backing indices are configured using the data stream's matching index template.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor IndexSettings(Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettings? indexSettings)
	{
		IndexSettingsDescriptor = null;
		IndexSettingsDescriptorAction = null;
		IndexSettingsValue = indexSettings;
		return Self;
	}

	public RestoreRequestDescriptor IndexSettings(Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettingsDescriptor descriptor)
	{
		IndexSettingsValue = null;
		IndexSettingsDescriptorAction = null;
		IndexSettingsDescriptor = descriptor;
		return Self;
	}

	public RestoreRequestDescriptor IndexSettings(Action<Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettingsDescriptor> configure)
	{
		IndexSettingsValue = null;
		IndexSettingsDescriptor = null;
		IndexSettingsDescriptorAction = configure;
		return Self;
	}

	/// <summary>
	/// <para>
	/// A comma-separated list of indices and data streams to restore.
	/// It supports a multi-target syntax.
	/// The default behavior is all regular indices and regular data streams in the snapshot.
	/// </para>
	/// <para>
	/// You can't use this parameter to restore system indices or system data streams.
	/// Use <c>feature_states</c> instead.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor Indices(Elastic.Clients.Elasticsearch.Serverless.Indices? indices)
	{
		IndicesValue = indices;
		return Self;
	}

	/// <summary>
	/// <para>
	/// If <c>false</c>, the entire restore operation will fail if one or more indices included in the snapshot do not have all primary shards available.
	/// </para>
	/// <para>
	/// If true, it allows restoring a partial snapshot of indices with unavailable shards.
	/// Only shards that were successfully included in the snapshot will be restored.
	/// All missing shards will be recreated as empty.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor Partial(bool? partial = true)
	{
		PartialValue = partial;
		return Self;
	}

	/// <summary>
	/// <para>
	/// A rename pattern to apply to restored data streams and indices.
	/// Data streams and indices matching the rename pattern will be renamed according to <c>rename_replacement</c>.
	/// </para>
	/// <para>
	/// The rename pattern is applied as defined by the regular expression that supports referencing the original text, according to the <c>appendReplacement</c> logic.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor RenamePattern(string? renamePattern)
	{
		RenamePatternValue = renamePattern;
		return Self;
	}

	/// <summary>
	/// <para>
	/// The rename replacement string that is used with the <c>rename_pattern</c>.
	/// </para>
	/// </summary>
	public RestoreRequestDescriptor RenameReplacement(string? renameReplacement)
	{
		RenameReplacementValue = renameReplacement;
		return Self;
	}

	protected override void Serialize(Utf8JsonWriter writer, JsonSerializerOptions options, IElasticsearchClientSettings settings)
	{
		writer.WriteStartObject();
		if (FeatureStatesValue is not null)
		{
			writer.WritePropertyName("feature_states");
			JsonSerializer.Serialize(writer, FeatureStatesValue, options);
		}

		if (IgnoreIndexSettingsValue is not null)
		{
			writer.WritePropertyName("ignore_index_settings");
			JsonSerializer.Serialize(writer, IgnoreIndexSettingsValue, options);
		}

		if (IgnoreUnavailableValue.HasValue)
		{
			writer.WritePropertyName("ignore_unavailable");
			writer.WriteBooleanValue(IgnoreUnavailableValue.Value);
		}

		if (IncludeAliasesValue.HasValue)
		{
			writer.WritePropertyName("include_aliases");
			writer.WriteBooleanValue(IncludeAliasesValue.Value);
		}

		if (IncludeGlobalStateValue.HasValue)
		{
			writer.WritePropertyName("include_global_state");
			writer.WriteBooleanValue(IncludeGlobalStateValue.Value);
		}

		if (IndexSettingsDescriptor is not null)
		{
			writer.WritePropertyName("index_settings");
			JsonSerializer.Serialize(writer, IndexSettingsDescriptor, options);
		}
		else if (IndexSettingsDescriptorAction is not null)
		{
			writer.WritePropertyName("index_settings");
			JsonSerializer.Serialize(writer, new Elastic.Clients.Elasticsearch.Serverless.IndexManagement.IndexSettingsDescriptor(IndexSettingsDescriptorAction), options);
		}
		else if (IndexSettingsValue is not null)
		{
			writer.WritePropertyName("index_settings");
			JsonSerializer.Serialize(writer, IndexSettingsValue, options);
		}

		if (IndicesValue is not null)
		{
			writer.WritePropertyName("indices");
			JsonSerializer.Serialize(writer, IndicesValue, options);
		}

		if (PartialValue.HasValue)
		{
			writer.WritePropertyName("partial");
			writer.WriteBooleanValue(PartialValue.Value);
		}

		if (!string.IsNullOrEmpty(RenamePatternValue))
		{
			writer.WritePropertyName("rename_pattern");
			writer.WriteStringValue(RenamePatternValue);
		}

		if (!string.IsNullOrEmpty(RenameReplacementValue))
		{
			writer.WritePropertyName("rename_replacement");
			writer.WriteStringValue(RenameReplacementValue);
		}

		writer.WriteEndObject();
	}
}