// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Serverless.Core;
using Elastic.Clients.Elasticsearch.Serverless.Fluent;
using Elastic.Clients.Elasticsearch.Serverless.Next;
using Elastic.Clients.Elasticsearch.Serverless.Serialization;
using Elastic.Transport;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Elastic.Clients.Elasticsearch.Serverless.Aggregations;

public partial interface IAggregate
{
	public string? Type { get; }
}

[JsonConverter(typeof(AggregateDictionaryConverter))]
public partial class AggregateDictionary : IsAReadOnlyDictionary<string, IAggregate>
{
	public AggregateDictionary(IReadOnlyDictionary<string, IAggregate> backingDictionary) : base(backingDictionary)
	{
	}

	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.AdjacencyMatrixAggregate? GetAdjacencyMatrix(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.AdjacencyMatrixAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.AutoDateHistogramAggregate? GetAutoDateHistogram(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.AutoDateHistogramAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.AverageAggregate? GetAverage(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.AverageAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.BoxplotAggregate? GetBoxplot(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.BoxplotAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.BucketMetricValueAggregate? GetBucketMetricValue(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.BucketMetricValueAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.CardinalityAggregate? GetCardinality(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.CardinalityAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.ChildrenAggregate? GetChildren(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ChildrenAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.CompositeAggregate? GetComposite(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.CompositeAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.CumulativeCardinalityAggregate? GetCumulativeCardinality(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.CumulativeCardinalityAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.DateHistogramAggregate? GetDateHistogram(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.DateHistogramAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.DateRangeAggregate? GetDateRange(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.DateRangeAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.DerivativeAggregate? GetDerivative(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.DerivativeAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.DoubleTermsAggregate? GetDoubleTerms(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.DoubleTermsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.ExtendedStatsAggregate? GetExtendedStats(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ExtendedStatsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.ExtendedStatsBucketAggregate? GetExtendedStatsBucket(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ExtendedStatsBucketAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.FilterAggregate? GetFilter(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.FilterAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.FiltersAggregate? GetFilters(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.FiltersAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.FrequentItemSetsAggregate? GetFrequentItemSets(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.FrequentItemSetsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoBoundsAggregate? GetGeoBounds(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoBoundsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoCentroidAggregate? GetGeoCentroid(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoCentroidAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoDistanceAggregate? GetGeoDistance(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoDistanceAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeohashGridAggregate? GetGeohashGrid(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeohashGridAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeohexGridAggregate? GetGeohexGrid(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeohexGridAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoLineAggregate? GetGeoLine(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoLineAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeotileGridAggregate? GetGeotileGrid(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeotileGridAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.GlobalAggregate? GetGlobal(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GlobalAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.HdrPercentileRanksAggregate? GetHdrPercentileRanks(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.HdrPercentileRanksAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.HdrPercentilesAggregate? GetHdrPercentiles(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.HdrPercentilesAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.HistogramAggregate? GetHistogram(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.HistogramAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.InferenceAggregate? GetInference(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.InferenceAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.IpPrefixAggregate? GetIpPrefix(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.IpPrefixAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.IpRangeAggregate? GetIpRange(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.IpRangeAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.LongRareTermsAggregate? GetLongRareTerms(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.LongRareTermsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.LongTermsAggregate? GetLongTerms(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.LongTermsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.MatrixStatsAggregate? GetMatrixStats(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.MatrixStatsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.MaxAggregate? GetMax(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.MaxAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.MedianAbsoluteDeviationAggregate? GetMedianAbsoluteDeviation(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.MedianAbsoluteDeviationAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.MinAggregate? GetMin(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.MinAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.MissingAggregate? GetMissing(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.MissingAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.MultiTermsAggregate? GetMultiTerms(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.MultiTermsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.NestedAggregate? GetNested(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.NestedAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.ParentAggregate? GetParent(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ParentAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.PercentilesBucketAggregate? GetPercentilesBucket(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.PercentilesBucketAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.RangeAggregate? GetRange(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.RangeAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.RateAggregate? GetRate(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.RateAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.ReverseNestedAggregate? GetReverseNested(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ReverseNestedAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.SamplerAggregate? GetSampler(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.SamplerAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.ScriptedMetricAggregate? GetScriptedMetric(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ScriptedMetricAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.SignificantLongTermsAggregate? GetSignificantLongTerms(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.SignificantLongTermsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.SignificantStringTermsAggregate? GetSignificantStringTerms(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.SignificantStringTermsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.SimpleValueAggregate? GetSimpleValue(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.SimpleValueAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.StatsAggregate? GetStats(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.StatsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.StatsBucketAggregate? GetStatsBucket(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.StatsBucketAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.StringRareTermsAggregate? GetStringRareTerms(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.StringRareTermsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.StringStatsAggregate? GetStringStats(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.StringStatsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.StringTermsAggregate? GetStringTerms(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.StringTermsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.SumAggregate? GetSum(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.SumAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.TDigestPercentileRanksAggregate? GetTDigestPercentileRanks(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.TDigestPercentileRanksAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.TDigestPercentilesAggregate? GetTDigestPercentiles(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.TDigestPercentilesAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.TimeSeriesAggregate? GetTimeSeries(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.TimeSeriesAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.TopHitsAggregate? GetTopHits(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.TopHitsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.TopMetricsAggregate? GetTopMetrics(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.TopMetricsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.TTestAggregate? GetTTest(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.TTestAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedRareTermsAggregate? GetUnmappedRareTerms(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedRareTermsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedSamplerAggregate? GetUnmappedSampler(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedSamplerAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedSignificantTermsAggregate? GetUnmappedSignificantTerms(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedSignificantTermsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedTermsAggregate? GetUnmappedTerms(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedTermsAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.ValueCountAggregate? GetValueCount(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ValueCountAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.VariableWidthHistogramAggregate? GetVariableWidthHistogram(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.VariableWidthHistogramAggregate>(key);
	public Elastic.Clients.Elasticsearch.Serverless.Aggregations.WeightedAverageAggregate? GetWeightedAverage(string key) => TryGet<Elastic.Clients.Elasticsearch.Serverless.Aggregations.WeightedAverageAggregate>(key);
	private T? TryGet<T>(string key) where T : class, IAggregate => BackingDictionary.TryGetValue(key, out var value) ? value as T : null;
}

internal sealed partial class AggregateDictionaryConverter : System.Text.Json.Serialization.JsonConverter<AggregateDictionary>
{
	public override AggregateDictionary Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
	{
		reader.ValidateToken(System.Text.Json.JsonTokenType.StartObject);
		var dictionary = new System.Collections.Generic.Dictionary<string, IAggregate>();
		while (reader.Read() && reader.TokenType is System.Text.Json.JsonTokenType.PropertyName)
		{
			ReadItem(ref reader, options, out string name, out IAggregate value);
			dictionary[name] = value;
		}

		reader.ValidateToken(System.Text.Json.JsonTokenType.EndObject);
		return new AggregateDictionary(dictionary);
	}

	public override void Write(System.Text.Json.Utf8JsonWriter writer, AggregateDictionary value, System.Text.Json.JsonSerializerOptions options)
	{
		writer.WriteStartObject();
		foreach (var pair in value)
		{
			WriteItem(writer, options, pair.Key, pair.Value);
		}

		writer.WriteEndObject();
	}

	internal static void ReadItem(ref System.Text.Json.Utf8JsonReader reader, System.Text.Json.JsonSerializerOptions options, out string name, out IAggregate value)
	{
		reader.ReadPropertyName(options, out string key);
		reader.Read();
		var parts = key.Split('#');
		if (parts.Length != 2)
		{
			throw new System.Text.Json.JsonException($"Unable to parse typed-key '{key}' for variant '{nameof(IAggregate)}'.");
		}

		var discriminator = parts[0];
		name = parts[1];
		value = discriminator switch
		{
			"adjacency_matrix" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.AdjacencyMatrixAggregate>(options),
			"auto_date_histogram" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.AutoDateHistogramAggregate>(options),
			"avg" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.AverageAggregate>(options),
			"boxplot" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.BoxplotAggregate>(options),
			"bucket_metric_value" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.BucketMetricValueAggregate>(options),
			"cardinality" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.CardinalityAggregate>(options),
			"children" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ChildrenAggregate>(options),
			"composite" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.CompositeAggregate>(options),
			"simple_long_value" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.CumulativeCardinalityAggregate>(options),
			"date_histogram" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.DateHistogramAggregate>(options),
			"date_range" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.DateRangeAggregate>(options),
			"derivative" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.DerivativeAggregate>(options),
			"dterms" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.DoubleTermsAggregate>(options),
			"extended_stats" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ExtendedStatsAggregate>(options),
			"extended_stats_bucket" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ExtendedStatsBucketAggregate>(options),
			"filter" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.FilterAggregate>(options),
			"filters" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.FiltersAggregate>(options),
			"frequent_item_sets" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.FrequentItemSetsAggregate>(options),
			"geo_bounds" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoBoundsAggregate>(options),
			"geo_centroid" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoCentroidAggregate>(options),
			"geo_distance" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoDistanceAggregate>(options),
			"geohash_grid" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeohashGridAggregate>(options),
			"geohex_grid" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeohexGridAggregate>(options),
			"geo_line" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoLineAggregate>(options),
			"geotile_grid" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeotileGridAggregate>(options),
			"global" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.GlobalAggregate>(options),
			"hdr_percentile_ranks" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.HdrPercentileRanksAggregate>(options),
			"hdr_percentiles" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.HdrPercentilesAggregate>(options),
			"histogram" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.HistogramAggregate>(options),
			"inference" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.InferenceAggregate>(options),
			"ip_prefix" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.IpPrefixAggregate>(options),
			"ip_range" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.IpRangeAggregate>(options),
			"lrareterms" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.LongRareTermsAggregate>(options),
			"lterms" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.LongTermsAggregate>(options),
			"matrix_stats" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.MatrixStatsAggregate>(options),
			"max" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.MaxAggregate>(options),
			"median_absolute_deviation" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.MedianAbsoluteDeviationAggregate>(options),
			"min" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.MinAggregate>(options),
			"missing" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.MissingAggregate>(options),
			"multi_terms" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.MultiTermsAggregate>(options),
			"nested" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.NestedAggregate>(options),
			"parent" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ParentAggregate>(options),
			"percentiles_bucket" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.PercentilesBucketAggregate>(options),
			"range" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.RangeAggregate>(options),
			"rate" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.RateAggregate>(options),
			"reverse_nested" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ReverseNestedAggregate>(options),
			"sampler" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.SamplerAggregate>(options),
			"scripted_metric" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ScriptedMetricAggregate>(options),
			"siglterms" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.SignificantLongTermsAggregate>(options),
			"sigsterms" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.SignificantStringTermsAggregate>(options),
			"simple_value" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.SimpleValueAggregate>(options),
			"stats" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.StatsAggregate>(options),
			"stats_bucket" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.StatsBucketAggregate>(options),
			"srareterms" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.StringRareTermsAggregate>(options),
			"string_stats" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.StringStatsAggregate>(options),
			"sterms" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.StringTermsAggregate>(options),
			"sum" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.SumAggregate>(options),
			"tdigest_percentile_ranks" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.TDigestPercentileRanksAggregate>(options),
			"tdigest_percentiles" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.TDigestPercentilesAggregate>(options),
			"time_series" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.TimeSeriesAggregate>(options),
			"top_hits" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.TopHitsAggregate>(options),
			"top_metrics" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.TopMetricsAggregate>(options),
			"t_test" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.TTestAggregate>(options),
			"umrareterms" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedRareTermsAggregate>(options),
			"unmapped_sampler" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedSamplerAggregate>(options),
			"umsigterms" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedSignificantTermsAggregate>(options),
			"umterms" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedTermsAggregate>(options),
			"value_count" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.ValueCountAggregate>(options),
			"variable_width_histogram" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.VariableWidthHistogramAggregate>(options),
			"weighted_avg" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Aggregations.WeightedAverageAggregate>(options),
			_ => throw new System.Text.Json.JsonException($"Variant '{discriminator}' is not supported for type '{nameof(IAggregate)}'.")
		};
	}

	internal static void WriteItem(System.Text.Json.Utf8JsonWriter writer, System.Text.Json.JsonSerializerOptions options, string name, IAggregate value)
	{
		var key = value.Type + '#' + name;
		switch (value)
		{
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.AdjacencyMatrixAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.AutoDateHistogramAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.AverageAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.BoxplotAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.BucketMetricValueAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.CardinalityAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.ChildrenAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.CompositeAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.CumulativeCardinalityAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.DateHistogramAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.DateRangeAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.DerivativeAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.DoubleTermsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.ExtendedStatsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.ExtendedStatsBucketAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.FilterAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.FiltersAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.FrequentItemSetsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoBoundsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoCentroidAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoDistanceAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeohashGridAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeohexGridAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeoLineAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.GeotileGridAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.GlobalAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.HdrPercentileRanksAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.HdrPercentilesAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.HistogramAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.InferenceAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.IpPrefixAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.IpRangeAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.LongRareTermsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.LongTermsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.MatrixStatsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.MaxAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.MedianAbsoluteDeviationAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.MinAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.MissingAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.MultiTermsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.NestedAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.ParentAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.PercentilesBucketAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.RangeAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.RateAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.ReverseNestedAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.SamplerAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.ScriptedMetricAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.SignificantLongTermsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.SignificantStringTermsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.SimpleValueAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.StatsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.StatsBucketAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.StringRareTermsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.StringStatsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.StringTermsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.SumAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.TDigestPercentileRanksAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.TDigestPercentilesAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.TimeSeriesAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.TopHitsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.TopMetricsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.TTestAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedRareTermsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedSamplerAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedSignificantTermsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.UnmappedTermsAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.ValueCountAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.VariableWidthHistogramAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			case Elastic.Clients.Elasticsearch.Serverless.Aggregations.WeightedAverageAggregate v:
				writer.WriteProperty(options, key, v);
				break;
			default:
				throw new System.Text.Json.JsonException($"Variant '{0}' is not supported for type '{nameof(IAggregate)}'.");
		}
	}
}