// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Serverless.Fluent;
using Elastic.Clients.Elasticsearch.Serverless.Next;
using Elastic.Clients.Elasticsearch.Serverless.Serialization;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Elastic.Clients.Elasticsearch.Serverless;

internal sealed partial class RRFRetrieverConverter : System.Text.Json.Serialization.JsonConverter<RRFRetriever>
{
	private static readonly System.Text.Json.JsonEncodedText PropFilter = System.Text.Json.JsonEncodedText.Encode("filter");
	private static readonly System.Text.Json.JsonEncodedText PropMinScore = System.Text.Json.JsonEncodedText.Encode("min_score");
	private static readonly System.Text.Json.JsonEncodedText PropRankConstant = System.Text.Json.JsonEncodedText.Encode("rank_constant");
	private static readonly System.Text.Json.JsonEncodedText PropRankWindowSize = System.Text.Json.JsonEncodedText.Encode("rank_window_size");
	private static readonly System.Text.Json.JsonEncodedText PropRetrievers = System.Text.Json.JsonEncodedText.Encode("retrievers");

	public override RRFRetriever Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
	{
		reader.ValidateToken(System.Text.Json.JsonTokenType.StartObject);
		LocalJsonProperty<ICollection<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.Query>?> propFilter = default;
		LocalJsonProperty<float?> propMinScore = default;
		LocalJsonProperty<int?> propRankConstant = default;
		LocalJsonProperty<int?> propRankWindowSize = default;
		LocalJsonProperty<ICollection<Elastic.Clients.Elasticsearch.Serverless.Retriever>> propRetrievers = default;
		while (reader.Read() && reader.TokenType is System.Text.Json.JsonTokenType.PropertyName)
		{
			if (propFilter.TryRead(ref reader, options, PropFilter, typeof(SingleOrManyMarker<IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.Query>?, Elastic.Clients.Elasticsearch.Serverless.QueryDsl.Query>)))
			{
				continue;
			}

			if (propMinScore.TryRead(ref reader, options, PropMinScore))
			{
				continue;
			}

			if (propRankConstant.TryRead(ref reader, options, PropRankConstant))
			{
				continue;
			}

			if (propRankWindowSize.TryRead(ref reader, options, PropRankWindowSize))
			{
				continue;
			}

			if (propRetrievers.TryRead(ref reader, options, PropRetrievers))
			{
				continue;
			}

			throw new System.Text.Json.JsonException($"Unknown JSON property '{reader.GetString()}' for type '{typeToConvert.Name}'.");
		}

		reader.ValidateToken(System.Text.Json.JsonTokenType.EndObject);
		return new RRFRetriever
		{
			Filter = propFilter.Value
,
			MinScore = propMinScore.Value
,
			RankConstant = propRankConstant.Value
,
			RankWindowSize = propRankWindowSize.Value
,
			Retrievers = propRetrievers.Value
		};
	}

	public override void Write(System.Text.Json.Utf8JsonWriter writer, RRFRetriever value, System.Text.Json.JsonSerializerOptions options)
	{
		writer.WriteStartObject();
		writer.WriteProperty(options, PropFilter, value.Filter, typeof(SingleOrManyMarker<IReadOnlyCollection<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.Query>?, Elastic.Clients.Elasticsearch.Serverless.QueryDsl.Query>));
		writer.WriteProperty(options, PropMinScore, value.MinScore);
		writer.WriteProperty(options, PropRankConstant, value.RankConstant);
		writer.WriteProperty(options, PropRankWindowSize, value.RankWindowSize);
		writer.WriteProperty(options, PropRetrievers, value.Retrievers);
		writer.WriteEndObject();
	}
}

[JsonConverter(typeof(RRFRetrieverConverter))]
public sealed partial class RRFRetriever
{
	/// <summary>
	/// <para>
	/// Query to filter the documents that can match.
	/// </para>
	/// </summary>
	public ICollection<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.Query>? Filter { get; set; }

	/// <summary>
	/// <para>
	/// Minimum _score for matching documents. Documents with a lower _score are not included in the top documents.
	/// </para>
	/// </summary>
	public float? MinScore { get; set; }

	/// <summary>
	/// <para>
	/// This value determines how much influence documents in individual result sets per query have over the final ranked result set.
	/// </para>
	/// </summary>
	public int? RankConstant { get; set; }

	/// <summary>
	/// <para>
	/// This value determines the size of the individual result sets per query.
	/// </para>
	/// </summary>
	public int? RankWindowSize { get; set; }

	/// <summary>
	/// <para>
	/// A list of child retrievers to specify which sets of returned top documents will have the RRF formula applied to them.
	/// </para>
	/// </summary>
	public ICollection<Elastic.Clients.Elasticsearch.Serverless.Retriever> Retrievers { get; set; }

	public static implicit operator Elastic.Clients.Elasticsearch.Serverless.Retriever(RRFRetriever rRFRetriever) => Elastic.Clients.Elasticsearch.Serverless.Retriever.Rrf(rRFRetriever);
}

public sealed partial class RRFRetrieverDescriptor<TDocument> : SerializableDescriptor<RRFRetrieverDescriptor<TDocument>>
{
	internal RRFRetrieverDescriptor(Action<RRFRetrieverDescriptor<TDocument>> configure) => configure.Invoke(this);

	public RRFRetrieverDescriptor() : base()
	{
	}

	private ICollection<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.Query>? FilterValue { get; set; }
	private Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor<TDocument> FilterDescriptor { get; set; }
	private Action<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor<TDocument>> FilterDescriptorAction { get; set; }
	private Action<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor<TDocument>>[] FilterDescriptorActions { get; set; }
	private float? MinScoreValue { get; set; }
	private int? RankConstantValue { get; set; }
	private int? RankWindowSizeValue { get; set; }
	private ICollection<Elastic.Clients.Elasticsearch.Serverless.Retriever> RetrieversValue { get; set; }
	private Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor<TDocument> RetrieversDescriptor { get; set; }
	private Action<Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor<TDocument>> RetrieversDescriptorAction { get; set; }
	private Action<Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor<TDocument>>[] RetrieversDescriptorActions { get; set; }

	/// <summary>
	/// <para>
	/// Query to filter the documents that can match.
	/// </para>
	/// </summary>
	public RRFRetrieverDescriptor<TDocument> Filter(ICollection<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.Query>? filter)
	{
		FilterDescriptor = null;
		FilterDescriptorAction = null;
		FilterDescriptorActions = null;
		FilterValue = filter;
		return Self;
	}

	public RRFRetrieverDescriptor<TDocument> Filter(Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor<TDocument> descriptor)
	{
		FilterValue = null;
		FilterDescriptorAction = null;
		FilterDescriptorActions = null;
		FilterDescriptor = descriptor;
		return Self;
	}

	public RRFRetrieverDescriptor<TDocument> Filter(Action<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor<TDocument>> configure)
	{
		FilterValue = null;
		FilterDescriptor = null;
		FilterDescriptorActions = null;
		FilterDescriptorAction = configure;
		return Self;
	}

	public RRFRetrieverDescriptor<TDocument> Filter(params Action<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor<TDocument>>[] configure)
	{
		FilterValue = null;
		FilterDescriptor = null;
		FilterDescriptorAction = null;
		FilterDescriptorActions = configure;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Minimum _score for matching documents. Documents with a lower _score are not included in the top documents.
	/// </para>
	/// </summary>
	public RRFRetrieverDescriptor<TDocument> MinScore(float? minScore)
	{
		MinScoreValue = minScore;
		return Self;
	}

	/// <summary>
	/// <para>
	/// This value determines how much influence documents in individual result sets per query have over the final ranked result set.
	/// </para>
	/// </summary>
	public RRFRetrieverDescriptor<TDocument> RankConstant(int? rankConstant)
	{
		RankConstantValue = rankConstant;
		return Self;
	}

	/// <summary>
	/// <para>
	/// This value determines the size of the individual result sets per query.
	/// </para>
	/// </summary>
	public RRFRetrieverDescriptor<TDocument> RankWindowSize(int? rankWindowSize)
	{
		RankWindowSizeValue = rankWindowSize;
		return Self;
	}

	/// <summary>
	/// <para>
	/// A list of child retrievers to specify which sets of returned top documents will have the RRF formula applied to them.
	/// </para>
	/// </summary>
	public RRFRetrieverDescriptor<TDocument> Retrievers(ICollection<Elastic.Clients.Elasticsearch.Serverless.Retriever> retrievers)
	{
		RetrieversDescriptor = null;
		RetrieversDescriptorAction = null;
		RetrieversDescriptorActions = null;
		RetrieversValue = retrievers;
		return Self;
	}

	public RRFRetrieverDescriptor<TDocument> Retrievers(Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor<TDocument> descriptor)
	{
		RetrieversValue = null;
		RetrieversDescriptorAction = null;
		RetrieversDescriptorActions = null;
		RetrieversDescriptor = descriptor;
		return Self;
	}

	public RRFRetrieverDescriptor<TDocument> Retrievers(Action<Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor<TDocument>> configure)
	{
		RetrieversValue = null;
		RetrieversDescriptor = null;
		RetrieversDescriptorActions = null;
		RetrieversDescriptorAction = configure;
		return Self;
	}

	public RRFRetrieverDescriptor<TDocument> Retrievers(params Action<Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor<TDocument>>[] configure)
	{
		RetrieversValue = null;
		RetrieversDescriptor = null;
		RetrieversDescriptorAction = null;
		RetrieversDescriptorActions = configure;
		return Self;
	}

	protected override void Serialize(Utf8JsonWriter writer, JsonSerializerOptions options, IElasticsearchClientSettings settings)
	{
		writer.WriteStartObject();
		if (FilterDescriptor is not null)
		{
			writer.WritePropertyName("filter");
			JsonSerializer.Serialize(writer, FilterDescriptor, options);
		}
		else if (FilterDescriptorAction is not null)
		{
			writer.WritePropertyName("filter");
			JsonSerializer.Serialize(writer, new Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor<TDocument>(FilterDescriptorAction), options);
		}
		else if (FilterDescriptorActions is not null)
		{
			writer.WritePropertyName("filter");
			if (FilterDescriptorActions.Length != 1)
				writer.WriteStartArray();
			foreach (var action in FilterDescriptorActions)
			{
				JsonSerializer.Serialize(writer, new Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor<TDocument>(action), options);
			}

			if (FilterDescriptorActions.Length != 1)
				writer.WriteEndArray();
		}
		else if (FilterValue is not null)
		{
			writer.WritePropertyName("filter");
			SingleOrManySerializationHelper.Serialize<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.Query>(FilterValue, writer, options);
		}

		if (MinScoreValue.HasValue)
		{
			writer.WritePropertyName("min_score");
			writer.WriteNumberValue(MinScoreValue.Value);
		}

		if (RankConstantValue.HasValue)
		{
			writer.WritePropertyName("rank_constant");
			writer.WriteNumberValue(RankConstantValue.Value);
		}

		if (RankWindowSizeValue.HasValue)
		{
			writer.WritePropertyName("rank_window_size");
			writer.WriteNumberValue(RankWindowSizeValue.Value);
		}

		if (RetrieversDescriptor is not null)
		{
			writer.WritePropertyName("retrievers");
			writer.WriteStartArray();
			JsonSerializer.Serialize(writer, RetrieversDescriptor, options);
			writer.WriteEndArray();
		}
		else if (RetrieversDescriptorAction is not null)
		{
			writer.WritePropertyName("retrievers");
			writer.WriteStartArray();
			JsonSerializer.Serialize(writer, new Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor<TDocument>(RetrieversDescriptorAction), options);
			writer.WriteEndArray();
		}
		else if (RetrieversDescriptorActions is not null)
		{
			writer.WritePropertyName("retrievers");
			writer.WriteStartArray();
			foreach (var action in RetrieversDescriptorActions)
			{
				JsonSerializer.Serialize(writer, new Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor<TDocument>(action), options);
			}

			writer.WriteEndArray();
		}
		else
		{
			writer.WritePropertyName("retrievers");
			JsonSerializer.Serialize(writer, RetrieversValue, options);
		}

		writer.WriteEndObject();
	}
}

public sealed partial class RRFRetrieverDescriptor : SerializableDescriptor<RRFRetrieverDescriptor>
{
	internal RRFRetrieverDescriptor(Action<RRFRetrieverDescriptor> configure) => configure.Invoke(this);

	public RRFRetrieverDescriptor() : base()
	{
	}

	private ICollection<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.Query>? FilterValue { get; set; }
	private Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor FilterDescriptor { get; set; }
	private Action<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor> FilterDescriptorAction { get; set; }
	private Action<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor>[] FilterDescriptorActions { get; set; }
	private float? MinScoreValue { get; set; }
	private int? RankConstantValue { get; set; }
	private int? RankWindowSizeValue { get; set; }
	private ICollection<Elastic.Clients.Elasticsearch.Serverless.Retriever> RetrieversValue { get; set; }
	private Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor RetrieversDescriptor { get; set; }
	private Action<Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor> RetrieversDescriptorAction { get; set; }
	private Action<Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor>[] RetrieversDescriptorActions { get; set; }

	/// <summary>
	/// <para>
	/// Query to filter the documents that can match.
	/// </para>
	/// </summary>
	public RRFRetrieverDescriptor Filter(ICollection<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.Query>? filter)
	{
		FilterDescriptor = null;
		FilterDescriptorAction = null;
		FilterDescriptorActions = null;
		FilterValue = filter;
		return Self;
	}

	public RRFRetrieverDescriptor Filter(Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor descriptor)
	{
		FilterValue = null;
		FilterDescriptorAction = null;
		FilterDescriptorActions = null;
		FilterDescriptor = descriptor;
		return Self;
	}

	public RRFRetrieverDescriptor Filter(Action<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor> configure)
	{
		FilterValue = null;
		FilterDescriptor = null;
		FilterDescriptorActions = null;
		FilterDescriptorAction = configure;
		return Self;
	}

	public RRFRetrieverDescriptor Filter(params Action<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor>[] configure)
	{
		FilterValue = null;
		FilterDescriptor = null;
		FilterDescriptorAction = null;
		FilterDescriptorActions = configure;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Minimum _score for matching documents. Documents with a lower _score are not included in the top documents.
	/// </para>
	/// </summary>
	public RRFRetrieverDescriptor MinScore(float? minScore)
	{
		MinScoreValue = minScore;
		return Self;
	}

	/// <summary>
	/// <para>
	/// This value determines how much influence documents in individual result sets per query have over the final ranked result set.
	/// </para>
	/// </summary>
	public RRFRetrieverDescriptor RankConstant(int? rankConstant)
	{
		RankConstantValue = rankConstant;
		return Self;
	}

	/// <summary>
	/// <para>
	/// This value determines the size of the individual result sets per query.
	/// </para>
	/// </summary>
	public RRFRetrieverDescriptor RankWindowSize(int? rankWindowSize)
	{
		RankWindowSizeValue = rankWindowSize;
		return Self;
	}

	/// <summary>
	/// <para>
	/// A list of child retrievers to specify which sets of returned top documents will have the RRF formula applied to them.
	/// </para>
	/// </summary>
	public RRFRetrieverDescriptor Retrievers(ICollection<Elastic.Clients.Elasticsearch.Serverless.Retriever> retrievers)
	{
		RetrieversDescriptor = null;
		RetrieversDescriptorAction = null;
		RetrieversDescriptorActions = null;
		RetrieversValue = retrievers;
		return Self;
	}

	public RRFRetrieverDescriptor Retrievers(Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor descriptor)
	{
		RetrieversValue = null;
		RetrieversDescriptorAction = null;
		RetrieversDescriptorActions = null;
		RetrieversDescriptor = descriptor;
		return Self;
	}

	public RRFRetrieverDescriptor Retrievers(Action<Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor> configure)
	{
		RetrieversValue = null;
		RetrieversDescriptor = null;
		RetrieversDescriptorActions = null;
		RetrieversDescriptorAction = configure;
		return Self;
	}

	public RRFRetrieverDescriptor Retrievers(params Action<Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor>[] configure)
	{
		RetrieversValue = null;
		RetrieversDescriptor = null;
		RetrieversDescriptorAction = null;
		RetrieversDescriptorActions = configure;
		return Self;
	}

	protected override void Serialize(Utf8JsonWriter writer, JsonSerializerOptions options, IElasticsearchClientSettings settings)
	{
		writer.WriteStartObject();
		if (FilterDescriptor is not null)
		{
			writer.WritePropertyName("filter");
			JsonSerializer.Serialize(writer, FilterDescriptor, options);
		}
		else if (FilterDescriptorAction is not null)
		{
			writer.WritePropertyName("filter");
			JsonSerializer.Serialize(writer, new Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor(FilterDescriptorAction), options);
		}
		else if (FilterDescriptorActions is not null)
		{
			writer.WritePropertyName("filter");
			if (FilterDescriptorActions.Length != 1)
				writer.WriteStartArray();
			foreach (var action in FilterDescriptorActions)
			{
				JsonSerializer.Serialize(writer, new Elastic.Clients.Elasticsearch.Serverless.QueryDsl.QueryDescriptor(action), options);
			}

			if (FilterDescriptorActions.Length != 1)
				writer.WriteEndArray();
		}
		else if (FilterValue is not null)
		{
			writer.WritePropertyName("filter");
			SingleOrManySerializationHelper.Serialize<Elastic.Clients.Elasticsearch.Serverless.QueryDsl.Query>(FilterValue, writer, options);
		}

		if (MinScoreValue.HasValue)
		{
			writer.WritePropertyName("min_score");
			writer.WriteNumberValue(MinScoreValue.Value);
		}

		if (RankConstantValue.HasValue)
		{
			writer.WritePropertyName("rank_constant");
			writer.WriteNumberValue(RankConstantValue.Value);
		}

		if (RankWindowSizeValue.HasValue)
		{
			writer.WritePropertyName("rank_window_size");
			writer.WriteNumberValue(RankWindowSizeValue.Value);
		}

		if (RetrieversDescriptor is not null)
		{
			writer.WritePropertyName("retrievers");
			writer.WriteStartArray();
			JsonSerializer.Serialize(writer, RetrieversDescriptor, options);
			writer.WriteEndArray();
		}
		else if (RetrieversDescriptorAction is not null)
		{
			writer.WritePropertyName("retrievers");
			writer.WriteStartArray();
			JsonSerializer.Serialize(writer, new Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor(RetrieversDescriptorAction), options);
			writer.WriteEndArray();
		}
		else if (RetrieversDescriptorActions is not null)
		{
			writer.WritePropertyName("retrievers");
			writer.WriteStartArray();
			foreach (var action in RetrieversDescriptorActions)
			{
				JsonSerializer.Serialize(writer, new Elastic.Clients.Elasticsearch.Serverless.RetrieverDescriptor(action), options);
			}

			writer.WriteEndArray();
		}
		else
		{
			writer.WritePropertyName("retrievers");
			JsonSerializer.Serialize(writer, RetrieversValue, options);
		}

		writer.WriteEndObject();
	}
}