// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Serverless.Fluent;
using Elastic.Clients.Elasticsearch.Serverless.Serialization;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Elastic.Clients.Elasticsearch.Serverless.Snapshot;

public sealed partial class AzureRepositorySettings
{
	/// <summary>
	/// <para>
	/// The path to the repository data within the container.
	/// It defaults to the root directory.
	/// </para>
	/// <para>
	/// NOTE: Don't set <c>base_path</c> when configuring a snapshot repository for Elastic Cloud Enterprise.
	/// Elastic Cloud Enterprise automatically generates the <c>base_path</c> for each deployment so that multiple deployments can share the same bucket.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("base_path")]
	public string? BasePath { get; set; }

	/// <summary>
	/// <para>
	/// Big files can be broken down into multiple smaller blobs in the blob store during snapshotting.
	/// It is not recommended to change this value from its default unless there is an explicit reason for limiting the size of blobs in the repository.
	/// Setting a value lower than the default can result in an increased number of API calls to the blob store during snapshot create and restore operations compared to using the default value and thus make both operations slower and more costly.
	/// Specify the chunk size as a byte unit, for example: <c>10MB</c>, <c>5KB</c>, 500B.
	/// The default varies by repository type.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("chunk_size")]
	public Elastic.Clients.Elasticsearch.Serverless.ByteSize? ChunkSize { get; set; }

	/// <summary>
	/// <para>
	/// The name of the Azure repository client to use.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("client")]
	public string? Client { get; set; }

	/// <summary>
	/// <para>
	/// When set to <c>true</c>, metadata files are stored in compressed format.
	/// This setting doesn't affect index files that are already compressed by default.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("compress")]
	public bool? Compress { get; set; }

	/// <summary>
	/// <para>
	/// The Azure container.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("container")]
	public string? Container { get; set; }

	/// <summary>
	/// <para>
	/// The maxmimum batch size, between 1 and 256, used for <c>BlobBatch</c> requests.
	/// Defaults to 256 which is the maximum number supported by the Azure blob batch API.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("delete_objects_max_size")]
	public int? DeleteObjectsMaxSize { get; set; }

	/// <summary>
	/// <para>
	/// Either <c>primary_only</c> or <c>secondary_only</c>.
	/// Note that if you set it to <c>secondary_only</c>, it will force <c>readonly</c> to <c>true</c>.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("location_mode")]
	public string? LocationMode { get; set; }

	/// <summary>
	/// <para>
	/// The maximum number of concurrent batch delete requests that will be submitted for any individual bulk delete with <c>BlobBatch</c>.
	/// Note that the effective number of concurrent deletes is further limited by the Azure client connection and event loop thread limits.
	/// Defaults to 10, minimum is 1, maximum is 100.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("max_concurrent_batch_deletes")]
	public int? MaxConcurrentBatchDeletes { get; set; }

	/// <summary>
	/// <para>
	/// The maximum snapshot restore rate per node.
	/// It defaults to unlimited.
	/// Note that restores are also throttled through recovery settings.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("max_restore_bytes_per_sec")]
	public Elastic.Clients.Elasticsearch.Serverless.ByteSize? MaxRestoreBytesPerSec { get; set; }

	/// <summary>
	/// <para>
	/// The maximum snapshot creation rate per node.
	/// It defaults to 40mb per second.
	/// Note that if the recovery settings for managed services are set, then it defaults to unlimited, and the rate is additionally throttled through recovery settings.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("max_snapshot_bytes_per_sec")]
	public Elastic.Clients.Elasticsearch.Serverless.ByteSize? MaxSnapshotBytesPerSec { get; set; }

	/// <summary>
	/// <para>
	/// If <c>true</c>, the repository is read-only.
	/// The cluster can retrieve and restore snapshots from the repository but not write to the repository or create snapshots in it.
	/// </para>
	/// <para>
	/// Only a cluster with write access can create snapshots in the repository.
	/// All other clusters connected to the repository should have the <c>readonly</c> parameter set to <c>true</c>.
	/// If <c>false</c>, the cluster can write to the repository and create snapshots in it.
	/// </para>
	/// <para>
	/// IMPORTANT: If you register the same snapshot repository with multiple clusters, only one cluster should have write access to the repository.
	/// Having multiple clusters write to the repository at the same time risks corrupting the contents of the repository.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("readonly")]
	public bool? Readonly { get; set; }
}

public sealed partial class AzureRepositorySettingsDescriptor : SerializableDescriptor<AzureRepositorySettingsDescriptor>
{
	internal AzureRepositorySettingsDescriptor(Action<AzureRepositorySettingsDescriptor> configure) => configure.Invoke(this);

	public AzureRepositorySettingsDescriptor() : base()
	{
	}

	private string? BasePathValue { get; set; }
	private Elastic.Clients.Elasticsearch.Serverless.ByteSize? ChunkSizeValue { get; set; }
	private string? ClientValue { get; set; }
	private bool? CompressValue { get; set; }
	private string? ContainerValue { get; set; }
	private int? DeleteObjectsMaxSizeValue { get; set; }
	private string? LocationModeValue { get; set; }
	private int? MaxConcurrentBatchDeletesValue { get; set; }
	private Elastic.Clients.Elasticsearch.Serverless.ByteSize? MaxRestoreBytesPerSecValue { get; set; }
	private Elastic.Clients.Elasticsearch.Serverless.ByteSize? MaxSnapshotBytesPerSecValue { get; set; }
	private bool? ReadonlyValue { get; set; }

	/// <summary>
	/// <para>
	/// The path to the repository data within the container.
	/// It defaults to the root directory.
	/// </para>
	/// <para>
	/// NOTE: Don't set <c>base_path</c> when configuring a snapshot repository for Elastic Cloud Enterprise.
	/// Elastic Cloud Enterprise automatically generates the <c>base_path</c> for each deployment so that multiple deployments can share the same bucket.
	/// </para>
	/// </summary>
	public AzureRepositorySettingsDescriptor BasePath(string? basePath)
	{
		BasePathValue = basePath;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Big files can be broken down into multiple smaller blobs in the blob store during snapshotting.
	/// It is not recommended to change this value from its default unless there is an explicit reason for limiting the size of blobs in the repository.
	/// Setting a value lower than the default can result in an increased number of API calls to the blob store during snapshot create and restore operations compared to using the default value and thus make both operations slower and more costly.
	/// Specify the chunk size as a byte unit, for example: <c>10MB</c>, <c>5KB</c>, 500B.
	/// The default varies by repository type.
	/// </para>
	/// </summary>
	public AzureRepositorySettingsDescriptor ChunkSize(Elastic.Clients.Elasticsearch.Serverless.ByteSize? chunkSize)
	{
		ChunkSizeValue = chunkSize;
		return Self;
	}

	/// <summary>
	/// <para>
	/// The name of the Azure repository client to use.
	/// </para>
	/// </summary>
	public AzureRepositorySettingsDescriptor Client(string? client)
	{
		ClientValue = client;
		return Self;
	}

	/// <summary>
	/// <para>
	/// When set to <c>true</c>, metadata files are stored in compressed format.
	/// This setting doesn't affect index files that are already compressed by default.
	/// </para>
	/// </summary>
	public AzureRepositorySettingsDescriptor Compress(bool? compress = true)
	{
		CompressValue = compress;
		return Self;
	}

	/// <summary>
	/// <para>
	/// The Azure container.
	/// </para>
	/// </summary>
	public AzureRepositorySettingsDescriptor Container(string? container)
	{
		ContainerValue = container;
		return Self;
	}

	/// <summary>
	/// <para>
	/// The maxmimum batch size, between 1 and 256, used for <c>BlobBatch</c> requests.
	/// Defaults to 256 which is the maximum number supported by the Azure blob batch API.
	/// </para>
	/// </summary>
	public AzureRepositorySettingsDescriptor DeleteObjectsMaxSize(int? deleteObjectsMaxSize)
	{
		DeleteObjectsMaxSizeValue = deleteObjectsMaxSize;
		return Self;
	}

	/// <summary>
	/// <para>
	/// Either <c>primary_only</c> or <c>secondary_only</c>.
	/// Note that if you set it to <c>secondary_only</c>, it will force <c>readonly</c> to <c>true</c>.
	/// </para>
	/// </summary>
	public AzureRepositorySettingsDescriptor LocationMode(string? locationMode)
	{
		LocationModeValue = locationMode;
		return Self;
	}

	/// <summary>
	/// <para>
	/// The maximum number of concurrent batch delete requests that will be submitted for any individual bulk delete with <c>BlobBatch</c>.
	/// Note that the effective number of concurrent deletes is further limited by the Azure client connection and event loop thread limits.
	/// Defaults to 10, minimum is 1, maximum is 100.
	/// </para>
	/// </summary>
	public AzureRepositorySettingsDescriptor MaxConcurrentBatchDeletes(int? maxConcurrentBatchDeletes)
	{
		MaxConcurrentBatchDeletesValue = maxConcurrentBatchDeletes;
		return Self;
	}

	/// <summary>
	/// <para>
	/// The maximum snapshot restore rate per node.
	/// It defaults to unlimited.
	/// Note that restores are also throttled through recovery settings.
	/// </para>
	/// </summary>
	public AzureRepositorySettingsDescriptor MaxRestoreBytesPerSec(Elastic.Clients.Elasticsearch.Serverless.ByteSize? maxRestoreBytesPerSec)
	{
		MaxRestoreBytesPerSecValue = maxRestoreBytesPerSec;
		return Self;
	}

	/// <summary>
	/// <para>
	/// The maximum snapshot creation rate per node.
	/// It defaults to 40mb per second.
	/// Note that if the recovery settings for managed services are set, then it defaults to unlimited, and the rate is additionally throttled through recovery settings.
	/// </para>
	/// </summary>
	public AzureRepositorySettingsDescriptor MaxSnapshotBytesPerSec(Elastic.Clients.Elasticsearch.Serverless.ByteSize? maxSnapshotBytesPerSec)
	{
		MaxSnapshotBytesPerSecValue = maxSnapshotBytesPerSec;
		return Self;
	}

	/// <summary>
	/// <para>
	/// If <c>true</c>, the repository is read-only.
	/// The cluster can retrieve and restore snapshots from the repository but not write to the repository or create snapshots in it.
	/// </para>
	/// <para>
	/// Only a cluster with write access can create snapshots in the repository.
	/// All other clusters connected to the repository should have the <c>readonly</c> parameter set to <c>true</c>.
	/// If <c>false</c>, the cluster can write to the repository and create snapshots in it.
	/// </para>
	/// <para>
	/// IMPORTANT: If you register the same snapshot repository with multiple clusters, only one cluster should have write access to the repository.
	/// Having multiple clusters write to the repository at the same time risks corrupting the contents of the repository.
	/// </para>
	/// </summary>
	public AzureRepositorySettingsDescriptor Readonly(bool? value = true)
	{
		ReadonlyValue = value;
		return Self;
	}

	protected override void Serialize(Utf8JsonWriter writer, JsonSerializerOptions options, IElasticsearchClientSettings settings)
	{
		writer.WriteStartObject();
		if (!string.IsNullOrEmpty(BasePathValue))
		{
			writer.WritePropertyName("base_path");
			writer.WriteStringValue(BasePathValue);
		}

		if (ChunkSizeValue is not null)
		{
			writer.WritePropertyName("chunk_size");
			JsonSerializer.Serialize(writer, ChunkSizeValue, options);
		}

		if (!string.IsNullOrEmpty(ClientValue))
		{
			writer.WritePropertyName("client");
			writer.WriteStringValue(ClientValue);
		}

		if (CompressValue.HasValue)
		{
			writer.WritePropertyName("compress");
			writer.WriteBooleanValue(CompressValue.Value);
		}

		if (!string.IsNullOrEmpty(ContainerValue))
		{
			writer.WritePropertyName("container");
			writer.WriteStringValue(ContainerValue);
		}

		if (DeleteObjectsMaxSizeValue.HasValue)
		{
			writer.WritePropertyName("delete_objects_max_size");
			writer.WriteNumberValue(DeleteObjectsMaxSizeValue.Value);
		}

		if (!string.IsNullOrEmpty(LocationModeValue))
		{
			writer.WritePropertyName("location_mode");
			writer.WriteStringValue(LocationModeValue);
		}

		if (MaxConcurrentBatchDeletesValue.HasValue)
		{
			writer.WritePropertyName("max_concurrent_batch_deletes");
			writer.WriteNumberValue(MaxConcurrentBatchDeletesValue.Value);
		}

		if (MaxRestoreBytesPerSecValue is not null)
		{
			writer.WritePropertyName("max_restore_bytes_per_sec");
			JsonSerializer.Serialize(writer, MaxRestoreBytesPerSecValue, options);
		}

		if (MaxSnapshotBytesPerSecValue is not null)
		{
			writer.WritePropertyName("max_snapshot_bytes_per_sec");
			JsonSerializer.Serialize(writer, MaxSnapshotBytesPerSecValue, options);
		}

		if (ReadonlyValue.HasValue)
		{
			writer.WritePropertyName("readonly");
			writer.WriteBooleanValue(ReadonlyValue.Value);
		}

		writer.WriteEndObject();
	}
}