// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Serverless.Fluent;
using Elastic.Clients.Elasticsearch.Serverless.Serialization;
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Elastic.Clients.Elasticsearch.Serverless.Snapshot;

public sealed partial class SnapshotStats
{
	/// <summary>
	/// <para>
	/// The number and size of files that still need to be copied as part of the incremental snapshot.
	/// For completed snapshots, this property indicates the number and size of files that were not already in the repository and were copied as part of the incremental snapshot.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("incremental")]
	public Elastic.Clients.Elasticsearch.Serverless.Snapshot.FileCountSnapshotStats Incremental { get; init; }

	/// <summary>
	/// <para>
	/// The time, in milliseconds, when the snapshot creation process started.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("start_time_in_millis")]
	public long StartTimeInMillis { get; init; }
	[JsonInclude, JsonPropertyName("time")]
	public Elastic.Clients.Elasticsearch.Serverless.Duration? Time { get; init; }

	/// <summary>
	/// <para>
	/// The total time, in milliseconds, that it took for the snapshot process to complete.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("time_in_millis")]
	public long TimeInMillis { get; init; }

	/// <summary>
	/// <para>
	/// The total number and size of files that are referenced by the snapshot.
	/// </para>
	/// </summary>
	[JsonInclude, JsonPropertyName("total")]
	public Elastic.Clients.Elasticsearch.Serverless.Snapshot.FileCountSnapshotStats Total { get; init; }
}