// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.
//
// ███╗   ██╗ ██████╗ ████████╗██╗ ██████╗███████╗
// ████╗  ██║██╔═══██╗╚══██╔══╝██║██╔════╝██╔════╝
// ██╔██╗ ██║██║   ██║   ██║   ██║██║     █████╗
// ██║╚██╗██║██║   ██║   ██║   ██║██║     ██╔══╝
// ██║ ╚████║╚██████╔╝   ██║   ██║╚██████╗███████╗
// ╚═╝  ╚═══╝ ╚═════╝    ╚═╝   ╚═╝ ╚═════╝╚══════╝
// ------------------------------------------------
//
// This file is automatically generated.
// Please do not edit these files manually.
//
// ------------------------------------------------

#nullable restore

using Elastic.Clients.Elasticsearch.Serverless.Core;
using Elastic.Clients.Elasticsearch.Serverless.Fluent;
using Elastic.Clients.Elasticsearch.Serverless.Next;
using Elastic.Clients.Elasticsearch.Serverless.Serialization;
using Elastic.Transport;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Elastic.Clients.Elasticsearch.Serverless.Mapping;

public partial class Properties : IsADictionary<Elastic.Clients.Elasticsearch.Serverless.PropertyName, IProperty>
{
	public Properties()
	{
	}

	public Properties(IDictionary<Elastic.Clients.Elasticsearch.Serverless.PropertyName, IProperty> container) : base(container)
	{
	}

	public void Add(Elastic.Clients.Elasticsearch.Serverless.PropertyName name, IProperty property) => BackingDictionary.Add(Sanitize(name), property);
	public bool TryGetProperty(Elastic.Clients.Elasticsearch.Serverless.PropertyName name, [NotNullWhen(returnValue: true)] out IProperty property) => BackingDictionary.TryGetValue(Sanitize(name), out property);

	public bool TryGetProperty<T>(Elastic.Clients.Elasticsearch.Serverless.PropertyName name, [NotNullWhen(returnValue: true)] out T? property) where T : class, IProperty
	{
		if (BackingDictionary.TryGetValue(Sanitize(name), out var matchedValue) && matchedValue is T finalValue)
		{
			property = finalValue;
			return true;
		}

		property = null;
		return false;
	}
}

public sealed partial class PropertiesDescriptor<TDocument> : IsADictionaryDescriptor<PropertiesDescriptor<TDocument>, Properties, Elastic.Clients.Elasticsearch.Serverless.PropertyName, IProperty>
{
	public PropertiesDescriptor() : base(new Properties())
	{
	}

	public PropertiesDescriptor(Properties properties) : base(properties ?? new Properties())
	{
	}

	public PropertiesDescriptor<TDocument> AggregateMetricDouble(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.AggregateMetricDoublePropertyDescriptor<TDocument>, AggregateMetricDoubleProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> AggregateMetricDouble(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.AggregateMetricDoublePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.AggregateMetricDoublePropertyDescriptor<TDocument>, AggregateMetricDoubleProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> AggregateMetricDouble(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, AggregateMetricDoubleProperty aggregateMetricDoubleProperty) => AssignVariant(propertyName, aggregateMetricDoubleProperty);
	public PropertiesDescriptor<TDocument> AggregateMetricDouble(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.AggregateMetricDoublePropertyDescriptor<TDocument>, AggregateMetricDoubleProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> AggregateMetricDouble(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.AggregateMetricDoublePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.AggregateMetricDoublePropertyDescriptor<TDocument>, AggregateMetricDoubleProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Binary(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.BinaryPropertyDescriptor<TDocument>, BinaryProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Binary(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.BinaryPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.BinaryPropertyDescriptor<TDocument>, BinaryProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Binary(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, BinaryProperty binaryProperty) => AssignVariant(propertyName, binaryProperty);
	public PropertiesDescriptor<TDocument> Binary(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.BinaryPropertyDescriptor<TDocument>, BinaryProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Binary(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.BinaryPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.BinaryPropertyDescriptor<TDocument>, BinaryProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Boolean(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.BooleanPropertyDescriptor<TDocument>, BooleanProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Boolean(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.BooleanPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.BooleanPropertyDescriptor<TDocument>, BooleanProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Boolean(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, BooleanProperty booleanProperty) => AssignVariant(propertyName, booleanProperty);
	public PropertiesDescriptor<TDocument> Boolean(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.BooleanPropertyDescriptor<TDocument>, BooleanProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Boolean(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.BooleanPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.BooleanPropertyDescriptor<TDocument>, BooleanProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> ByteNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ByteNumberPropertyDescriptor<TDocument>, ByteNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> ByteNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.ByteNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ByteNumberPropertyDescriptor<TDocument>, ByteNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> ByteNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, ByteNumberProperty byteNumberProperty) => AssignVariant(propertyName, byteNumberProperty);
	public PropertiesDescriptor<TDocument> ByteNumber(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ByteNumberPropertyDescriptor<TDocument>, ByteNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> ByteNumber(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.ByteNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ByteNumberPropertyDescriptor<TDocument>, ByteNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Completion(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.CompletionPropertyDescriptor<TDocument>, CompletionProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Completion(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.CompletionPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.CompletionPropertyDescriptor<TDocument>, CompletionProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Completion(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, CompletionProperty completionProperty) => AssignVariant(propertyName, completionProperty);
	public PropertiesDescriptor<TDocument> Completion(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.CompletionPropertyDescriptor<TDocument>, CompletionProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Completion(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.CompletionPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.CompletionPropertyDescriptor<TDocument>, CompletionProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> ConstantKeyword(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ConstantKeywordPropertyDescriptor<TDocument>, ConstantKeywordProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> ConstantKeyword(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.ConstantKeywordPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ConstantKeywordPropertyDescriptor<TDocument>, ConstantKeywordProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> ConstantKeyword(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, ConstantKeywordProperty constantKeywordProperty) => AssignVariant(propertyName, constantKeywordProperty);
	public PropertiesDescriptor<TDocument> ConstantKeyword(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ConstantKeywordPropertyDescriptor<TDocument>, ConstantKeywordProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> ConstantKeyword(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.ConstantKeywordPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ConstantKeywordPropertyDescriptor<TDocument>, ConstantKeywordProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> DateNanos(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateNanosPropertyDescriptor<TDocument>, DateNanosProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> DateNanos(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateNanosPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateNanosPropertyDescriptor<TDocument>, DateNanosProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> DateNanos(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, DateNanosProperty dateNanosProperty) => AssignVariant(propertyName, dateNanosProperty);
	public PropertiesDescriptor<TDocument> DateNanos(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateNanosPropertyDescriptor<TDocument>, DateNanosProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> DateNanos(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateNanosPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateNanosPropertyDescriptor<TDocument>, DateNanosProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Date(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DatePropertyDescriptor<TDocument>, DateProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Date(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DatePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DatePropertyDescriptor<TDocument>, DateProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Date(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, DateProperty dateProperty) => AssignVariant(propertyName, dateProperty);
	public PropertiesDescriptor<TDocument> Date(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DatePropertyDescriptor<TDocument>, DateProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Date(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DatePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DatePropertyDescriptor<TDocument>, DateProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> DateRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateRangePropertyDescriptor<TDocument>, DateRangeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> DateRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateRangePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateRangePropertyDescriptor<TDocument>, DateRangeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> DateRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, DateRangeProperty dateRangeProperty) => AssignVariant(propertyName, dateRangeProperty);
	public PropertiesDescriptor<TDocument> DateRange(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateRangePropertyDescriptor<TDocument>, DateRangeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> DateRange(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateRangePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateRangePropertyDescriptor<TDocument>, DateRangeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> DenseVector(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DenseVectorPropertyDescriptor<TDocument>, DenseVectorProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> DenseVector(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DenseVectorPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DenseVectorPropertyDescriptor<TDocument>, DenseVectorProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> DenseVector(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, DenseVectorProperty denseVectorProperty) => AssignVariant(propertyName, denseVectorProperty);
	public PropertiesDescriptor<TDocument> DenseVector(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DenseVectorPropertyDescriptor<TDocument>, DenseVectorProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> DenseVector(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DenseVectorPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DenseVectorPropertyDescriptor<TDocument>, DenseVectorProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> DoubleNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleNumberPropertyDescriptor<TDocument>, DoubleNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> DoubleNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleNumberPropertyDescriptor<TDocument>, DoubleNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> DoubleNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, DoubleNumberProperty doubleNumberProperty) => AssignVariant(propertyName, doubleNumberProperty);
	public PropertiesDescriptor<TDocument> DoubleNumber(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleNumberPropertyDescriptor<TDocument>, DoubleNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> DoubleNumber(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleNumberPropertyDescriptor<TDocument>, DoubleNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> DoubleRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleRangePropertyDescriptor<TDocument>, DoubleRangeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> DoubleRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleRangePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleRangePropertyDescriptor<TDocument>, DoubleRangeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> DoubleRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, DoubleRangeProperty doubleRangeProperty) => AssignVariant(propertyName, doubleRangeProperty);
	public PropertiesDescriptor<TDocument> DoubleRange(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleRangePropertyDescriptor<TDocument>, DoubleRangeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> DoubleRange(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleRangePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleRangePropertyDescriptor<TDocument>, DoubleRangeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Dynamic(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DynamicPropertyDescriptor<TDocument>, DynamicProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Dynamic(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DynamicPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DynamicPropertyDescriptor<TDocument>, DynamicProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Dynamic(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, DynamicProperty dynamicProperty) => AssignVariant(propertyName, dynamicProperty);
	public PropertiesDescriptor<TDocument> Dynamic(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DynamicPropertyDescriptor<TDocument>, DynamicProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Dynamic(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.DynamicPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.DynamicPropertyDescriptor<TDocument>, DynamicProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> FieldAlias(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FieldAliasPropertyDescriptor<TDocument>, FieldAliasProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> FieldAlias(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.FieldAliasPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FieldAliasPropertyDescriptor<TDocument>, FieldAliasProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> FieldAlias(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, FieldAliasProperty fieldAliasProperty) => AssignVariant(propertyName, fieldAliasProperty);
	public PropertiesDescriptor<TDocument> FieldAlias(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FieldAliasPropertyDescriptor<TDocument>, FieldAliasProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> FieldAlias(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.FieldAliasPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FieldAliasPropertyDescriptor<TDocument>, FieldAliasProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Flattened(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FlattenedPropertyDescriptor<TDocument>, FlattenedProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Flattened(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.FlattenedPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FlattenedPropertyDescriptor<TDocument>, FlattenedProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Flattened(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, FlattenedProperty flattenedProperty) => AssignVariant(propertyName, flattenedProperty);
	public PropertiesDescriptor<TDocument> Flattened(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FlattenedPropertyDescriptor<TDocument>, FlattenedProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Flattened(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.FlattenedPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FlattenedPropertyDescriptor<TDocument>, FlattenedProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> FloatNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatNumberPropertyDescriptor<TDocument>, FloatNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> FloatNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatNumberPropertyDescriptor<TDocument>, FloatNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> FloatNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, FloatNumberProperty floatNumberProperty) => AssignVariant(propertyName, floatNumberProperty);
	public PropertiesDescriptor<TDocument> FloatNumber(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatNumberPropertyDescriptor<TDocument>, FloatNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> FloatNumber(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatNumberPropertyDescriptor<TDocument>, FloatNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> FloatRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatRangePropertyDescriptor<TDocument>, FloatRangeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> FloatRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatRangePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatRangePropertyDescriptor<TDocument>, FloatRangeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> FloatRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, FloatRangeProperty floatRangeProperty) => AssignVariant(propertyName, floatRangeProperty);
	public PropertiesDescriptor<TDocument> FloatRange(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatRangePropertyDescriptor<TDocument>, FloatRangeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> FloatRange(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatRangePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatRangePropertyDescriptor<TDocument>, FloatRangeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> GeoPoint(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoPointPropertyDescriptor<TDocument>, GeoPointProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> GeoPoint(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoPointPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoPointPropertyDescriptor<TDocument>, GeoPointProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> GeoPoint(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, GeoPointProperty geoPointProperty) => AssignVariant(propertyName, geoPointProperty);
	public PropertiesDescriptor<TDocument> GeoPoint(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoPointPropertyDescriptor<TDocument>, GeoPointProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> GeoPoint(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoPointPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoPointPropertyDescriptor<TDocument>, GeoPointProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> GeoShape(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoShapePropertyDescriptor<TDocument>, GeoShapeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> GeoShape(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoShapePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoShapePropertyDescriptor<TDocument>, GeoShapeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> GeoShape(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, GeoShapeProperty geoShapeProperty) => AssignVariant(propertyName, geoShapeProperty);
	public PropertiesDescriptor<TDocument> GeoShape(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoShapePropertyDescriptor<TDocument>, GeoShapeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> GeoShape(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoShapePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoShapePropertyDescriptor<TDocument>, GeoShapeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> HalfFloatNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.HalfFloatNumberPropertyDescriptor<TDocument>, HalfFloatNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> HalfFloatNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.HalfFloatNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.HalfFloatNumberPropertyDescriptor<TDocument>, HalfFloatNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> HalfFloatNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, HalfFloatNumberProperty halfFloatNumberProperty) => AssignVariant(propertyName, halfFloatNumberProperty);
	public PropertiesDescriptor<TDocument> HalfFloatNumber(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.HalfFloatNumberPropertyDescriptor<TDocument>, HalfFloatNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> HalfFloatNumber(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.HalfFloatNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.HalfFloatNumberPropertyDescriptor<TDocument>, HalfFloatNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Histogram(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.HistogramPropertyDescriptor<TDocument>, HistogramProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Histogram(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.HistogramPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.HistogramPropertyDescriptor<TDocument>, HistogramProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Histogram(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, HistogramProperty histogramProperty) => AssignVariant(propertyName, histogramProperty);
	public PropertiesDescriptor<TDocument> Histogram(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.HistogramPropertyDescriptor<TDocument>, HistogramProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Histogram(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.HistogramPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.HistogramPropertyDescriptor<TDocument>, HistogramProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> IcuCollation(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IcuCollationPropertyDescriptor<TDocument>, IcuCollationProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> IcuCollation(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.IcuCollationPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IcuCollationPropertyDescriptor<TDocument>, IcuCollationProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> IcuCollation(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, IcuCollationProperty icuCollationProperty) => AssignVariant(propertyName, icuCollationProperty);
	public PropertiesDescriptor<TDocument> IcuCollation(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IcuCollationPropertyDescriptor<TDocument>, IcuCollationProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> IcuCollation(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.IcuCollationPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IcuCollationPropertyDescriptor<TDocument>, IcuCollationProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> IntegerNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerNumberPropertyDescriptor<TDocument>, IntegerNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> IntegerNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerNumberPropertyDescriptor<TDocument>, IntegerNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> IntegerNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, IntegerNumberProperty integerNumberProperty) => AssignVariant(propertyName, integerNumberProperty);
	public PropertiesDescriptor<TDocument> IntegerNumber(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerNumberPropertyDescriptor<TDocument>, IntegerNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> IntegerNumber(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerNumberPropertyDescriptor<TDocument>, IntegerNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> IntegerRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerRangePropertyDescriptor<TDocument>, IntegerRangeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> IntegerRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerRangePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerRangePropertyDescriptor<TDocument>, IntegerRangeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> IntegerRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, IntegerRangeProperty integerRangeProperty) => AssignVariant(propertyName, integerRangeProperty);
	public PropertiesDescriptor<TDocument> IntegerRange(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerRangePropertyDescriptor<TDocument>, IntegerRangeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> IntegerRange(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerRangePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerRangePropertyDescriptor<TDocument>, IntegerRangeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Ip(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpPropertyDescriptor<TDocument>, IpProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Ip(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpPropertyDescriptor<TDocument>, IpProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Ip(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, IpProperty ipProperty) => AssignVariant(propertyName, ipProperty);
	public PropertiesDescriptor<TDocument> Ip(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpPropertyDescriptor<TDocument>, IpProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Ip(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpPropertyDescriptor<TDocument>, IpProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> IpRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpRangePropertyDescriptor<TDocument>, IpRangeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> IpRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpRangePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpRangePropertyDescriptor<TDocument>, IpRangeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> IpRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, IpRangeProperty ipRangeProperty) => AssignVariant(propertyName, ipRangeProperty);
	public PropertiesDescriptor<TDocument> IpRange(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpRangePropertyDescriptor<TDocument>, IpRangeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> IpRange(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpRangePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpRangePropertyDescriptor<TDocument>, IpRangeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Join(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.JoinPropertyDescriptor<TDocument>, JoinProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Join(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.JoinPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.JoinPropertyDescriptor<TDocument>, JoinProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Join(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, JoinProperty joinProperty) => AssignVariant(propertyName, joinProperty);
	public PropertiesDescriptor<TDocument> Join(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.JoinPropertyDescriptor<TDocument>, JoinProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Join(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.JoinPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.JoinPropertyDescriptor<TDocument>, JoinProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Keyword(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.KeywordPropertyDescriptor<TDocument>, KeywordProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Keyword(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.KeywordPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.KeywordPropertyDescriptor<TDocument>, KeywordProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Keyword(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, KeywordProperty keywordProperty) => AssignVariant(propertyName, keywordProperty);
	public PropertiesDescriptor<TDocument> Keyword(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.KeywordPropertyDescriptor<TDocument>, KeywordProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Keyword(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.KeywordPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.KeywordPropertyDescriptor<TDocument>, KeywordProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> LongNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongNumberPropertyDescriptor<TDocument>, LongNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> LongNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongNumberPropertyDescriptor<TDocument>, LongNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> LongNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, LongNumberProperty longNumberProperty) => AssignVariant(propertyName, longNumberProperty);
	public PropertiesDescriptor<TDocument> LongNumber(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongNumberPropertyDescriptor<TDocument>, LongNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> LongNumber(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongNumberPropertyDescriptor<TDocument>, LongNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> LongRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongRangePropertyDescriptor<TDocument>, LongRangeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> LongRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongRangePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongRangePropertyDescriptor<TDocument>, LongRangeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> LongRange(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, LongRangeProperty longRangeProperty) => AssignVariant(propertyName, longRangeProperty);
	public PropertiesDescriptor<TDocument> LongRange(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongRangePropertyDescriptor<TDocument>, LongRangeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> LongRange(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongRangePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongRangePropertyDescriptor<TDocument>, LongRangeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> MatchOnlyText(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.MatchOnlyTextPropertyDescriptor<TDocument>, MatchOnlyTextProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> MatchOnlyText(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.MatchOnlyTextPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.MatchOnlyTextPropertyDescriptor<TDocument>, MatchOnlyTextProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> MatchOnlyText(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, MatchOnlyTextProperty matchOnlyTextProperty) => AssignVariant(propertyName, matchOnlyTextProperty);
	public PropertiesDescriptor<TDocument> MatchOnlyText(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.MatchOnlyTextPropertyDescriptor<TDocument>, MatchOnlyTextProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> MatchOnlyText(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.MatchOnlyTextPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.MatchOnlyTextPropertyDescriptor<TDocument>, MatchOnlyTextProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Murmur3Hash(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.Murmur3HashPropertyDescriptor<TDocument>, Murmur3HashProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Murmur3Hash(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.Murmur3HashPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.Murmur3HashPropertyDescriptor<TDocument>, Murmur3HashProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Murmur3Hash(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Murmur3HashProperty murmur3HashProperty) => AssignVariant(propertyName, murmur3HashProperty);
	public PropertiesDescriptor<TDocument> Murmur3Hash(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.Murmur3HashPropertyDescriptor<TDocument>, Murmur3HashProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Murmur3Hash(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.Murmur3HashPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.Murmur3HashPropertyDescriptor<TDocument>, Murmur3HashProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Nested(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.NestedPropertyDescriptor<TDocument>, NestedProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Nested(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.NestedPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.NestedPropertyDescriptor<TDocument>, NestedProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Nested(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, NestedProperty nestedProperty) => AssignVariant(propertyName, nestedProperty);
	public PropertiesDescriptor<TDocument> Nested(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.NestedPropertyDescriptor<TDocument>, NestedProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Nested(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.NestedPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.NestedPropertyDescriptor<TDocument>, NestedProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Object(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ObjectPropertyDescriptor<TDocument>, ObjectProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Object(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.ObjectPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ObjectPropertyDescriptor<TDocument>, ObjectProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Object(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, ObjectProperty objectProperty) => AssignVariant(propertyName, objectProperty);
	public PropertiesDescriptor<TDocument> Object(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ObjectPropertyDescriptor<TDocument>, ObjectProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Object(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.ObjectPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ObjectPropertyDescriptor<TDocument>, ObjectProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> PassthroughObject(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.PassthroughObjectPropertyDescriptor<TDocument>, PassthroughObjectProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> PassthroughObject(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.PassthroughObjectPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.PassthroughObjectPropertyDescriptor<TDocument>, PassthroughObjectProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> PassthroughObject(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, PassthroughObjectProperty passthroughObjectProperty) => AssignVariant(propertyName, passthroughObjectProperty);
	public PropertiesDescriptor<TDocument> PassthroughObject(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.PassthroughObjectPropertyDescriptor<TDocument>, PassthroughObjectProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> PassthroughObject(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.PassthroughObjectPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.PassthroughObjectPropertyDescriptor<TDocument>, PassthroughObjectProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Percolator(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.PercolatorPropertyDescriptor<TDocument>, PercolatorProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Percolator(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.PercolatorPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.PercolatorPropertyDescriptor<TDocument>, PercolatorProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Percolator(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, PercolatorProperty percolatorProperty) => AssignVariant(propertyName, percolatorProperty);
	public PropertiesDescriptor<TDocument> Percolator(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.PercolatorPropertyDescriptor<TDocument>, PercolatorProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Percolator(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.PercolatorPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.PercolatorPropertyDescriptor<TDocument>, PercolatorProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Point(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.PointPropertyDescriptor<TDocument>, PointProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Point(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.PointPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.PointPropertyDescriptor<TDocument>, PointProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Point(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, PointProperty pointProperty) => AssignVariant(propertyName, pointProperty);
	public PropertiesDescriptor<TDocument> Point(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.PointPropertyDescriptor<TDocument>, PointProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Point(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.PointPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.PointPropertyDescriptor<TDocument>, PointProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> RankFeature(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturePropertyDescriptor<TDocument>, RankFeatureProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> RankFeature(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturePropertyDescriptor<TDocument>, RankFeatureProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> RankFeature(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, RankFeatureProperty rankFeatureProperty) => AssignVariant(propertyName, rankFeatureProperty);
	public PropertiesDescriptor<TDocument> RankFeature(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturePropertyDescriptor<TDocument>, RankFeatureProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> RankFeature(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturePropertyDescriptor<TDocument>, RankFeatureProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> RankFeatures(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturesPropertyDescriptor<TDocument>, RankFeaturesProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> RankFeatures(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturesPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturesPropertyDescriptor<TDocument>, RankFeaturesProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> RankFeatures(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, RankFeaturesProperty rankFeaturesProperty) => AssignVariant(propertyName, rankFeaturesProperty);
	public PropertiesDescriptor<TDocument> RankFeatures(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturesPropertyDescriptor<TDocument>, RankFeaturesProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> RankFeatures(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturesPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturesPropertyDescriptor<TDocument>, RankFeaturesProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> ScaledFloatNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ScaledFloatNumberPropertyDescriptor<TDocument>, ScaledFloatNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> ScaledFloatNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.ScaledFloatNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ScaledFloatNumberPropertyDescriptor<TDocument>, ScaledFloatNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> ScaledFloatNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, ScaledFloatNumberProperty scaledFloatNumberProperty) => AssignVariant(propertyName, scaledFloatNumberProperty);
	public PropertiesDescriptor<TDocument> ScaledFloatNumber(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ScaledFloatNumberPropertyDescriptor<TDocument>, ScaledFloatNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> ScaledFloatNumber(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.ScaledFloatNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ScaledFloatNumberPropertyDescriptor<TDocument>, ScaledFloatNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> SearchAsYouType(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.SearchAsYouTypePropertyDescriptor<TDocument>, SearchAsYouTypeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> SearchAsYouType(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.SearchAsYouTypePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.SearchAsYouTypePropertyDescriptor<TDocument>, SearchAsYouTypeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> SearchAsYouType(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, SearchAsYouTypeProperty searchAsYouTypeProperty) => AssignVariant(propertyName, searchAsYouTypeProperty);
	public PropertiesDescriptor<TDocument> SearchAsYouType(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.SearchAsYouTypePropertyDescriptor<TDocument>, SearchAsYouTypeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> SearchAsYouType(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.SearchAsYouTypePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.SearchAsYouTypePropertyDescriptor<TDocument>, SearchAsYouTypeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> SemanticText(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.SemanticTextPropertyDescriptor, SemanticTextProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> SemanticText(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.SemanticTextPropertyDescriptor> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.SemanticTextPropertyDescriptor, SemanticTextProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> SemanticText(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, SemanticTextProperty semanticTextProperty) => AssignVariant(propertyName, semanticTextProperty);
	public PropertiesDescriptor<TDocument> SemanticText(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.SemanticTextPropertyDescriptor, SemanticTextProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> SemanticText(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.SemanticTextPropertyDescriptor> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.SemanticTextPropertyDescriptor, SemanticTextProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Shape(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShapePropertyDescriptor<TDocument>, ShapeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Shape(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShapePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShapePropertyDescriptor<TDocument>, ShapeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Shape(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, ShapeProperty shapeProperty) => AssignVariant(propertyName, shapeProperty);
	public PropertiesDescriptor<TDocument> Shape(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShapePropertyDescriptor<TDocument>, ShapeProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Shape(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShapePropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShapePropertyDescriptor<TDocument>, ShapeProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> ShortNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShortNumberPropertyDescriptor<TDocument>, ShortNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> ShortNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShortNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShortNumberPropertyDescriptor<TDocument>, ShortNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> ShortNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, ShortNumberProperty shortNumberProperty) => AssignVariant(propertyName, shortNumberProperty);
	public PropertiesDescriptor<TDocument> ShortNumber(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShortNumberPropertyDescriptor<TDocument>, ShortNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> ShortNumber(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShortNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShortNumberPropertyDescriptor<TDocument>, ShortNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> SparseVector(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.SparseVectorPropertyDescriptor<TDocument>, SparseVectorProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> SparseVector(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.SparseVectorPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.SparseVectorPropertyDescriptor<TDocument>, SparseVectorProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> SparseVector(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, SparseVectorProperty sparseVectorProperty) => AssignVariant(propertyName, sparseVectorProperty);
	public PropertiesDescriptor<TDocument> SparseVector(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.SparseVectorPropertyDescriptor<TDocument>, SparseVectorProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> SparseVector(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.SparseVectorPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.SparseVectorPropertyDescriptor<TDocument>, SparseVectorProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Text(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.TextPropertyDescriptor<TDocument>, TextProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Text(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.TextPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.TextPropertyDescriptor<TDocument>, TextProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Text(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, TextProperty textProperty) => AssignVariant(propertyName, textProperty);
	public PropertiesDescriptor<TDocument> Text(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.TextPropertyDescriptor<TDocument>, TextProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Text(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.TextPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.TextPropertyDescriptor<TDocument>, TextProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> TokenCount(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.TokenCountPropertyDescriptor<TDocument>, TokenCountProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> TokenCount(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.TokenCountPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.TokenCountPropertyDescriptor<TDocument>, TokenCountProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> TokenCount(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, TokenCountProperty tokenCountProperty) => AssignVariant(propertyName, tokenCountProperty);
	public PropertiesDescriptor<TDocument> TokenCount(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.TokenCountPropertyDescriptor<TDocument>, TokenCountProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> TokenCount(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.TokenCountPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.TokenCountPropertyDescriptor<TDocument>, TokenCountProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> UnsignedLongNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.UnsignedLongNumberPropertyDescriptor<TDocument>, UnsignedLongNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> UnsignedLongNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.UnsignedLongNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.UnsignedLongNumberPropertyDescriptor<TDocument>, UnsignedLongNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> UnsignedLongNumber(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, UnsignedLongNumberProperty unsignedLongNumberProperty) => AssignVariant(propertyName, unsignedLongNumberProperty);
	public PropertiesDescriptor<TDocument> UnsignedLongNumber(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.UnsignedLongNumberPropertyDescriptor<TDocument>, UnsignedLongNumberProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> UnsignedLongNumber(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.UnsignedLongNumberPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.UnsignedLongNumberPropertyDescriptor<TDocument>, UnsignedLongNumberProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Version(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.VersionPropertyDescriptor<TDocument>, VersionProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Version(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.VersionPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.VersionPropertyDescriptor<TDocument>, VersionProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Version(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, VersionProperty versionProperty) => AssignVariant(propertyName, versionProperty);
	public PropertiesDescriptor<TDocument> Version(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.VersionPropertyDescriptor<TDocument>, VersionProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Version(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.VersionPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.VersionPropertyDescriptor<TDocument>, VersionProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Wildcard(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.WildcardPropertyDescriptor<TDocument>, WildcardProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Wildcard(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.WildcardPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.WildcardPropertyDescriptor<TDocument>, WildcardProperty>(propertyName, configure);
	public PropertiesDescriptor<TDocument> Wildcard(Elastic.Clients.Elasticsearch.Serverless.PropertyName propertyName, WildcardProperty wildcardProperty) => AssignVariant(propertyName, wildcardProperty);
	public PropertiesDescriptor<TDocument> Wildcard(Expression<Func<TDocument, object>> propertyName) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.WildcardPropertyDescriptor<TDocument>, WildcardProperty>(propertyName, null);
	public PropertiesDescriptor<TDocument> Wildcard(Expression<Func<TDocument, object>> propertyName, Action<Elastic.Clients.Elasticsearch.Serverless.Mapping.WildcardPropertyDescriptor<TDocument>> configure) => AssignVariant<Elastic.Clients.Elasticsearch.Serverless.Mapping.WildcardPropertyDescriptor<TDocument>, WildcardProperty>(propertyName, configure);
}

internal sealed partial class PropertyInterfaceConverter : System.Text.Json.Serialization.JsonConverter<IProperty>
{
	private static readonly System.Text.Json.JsonEncodedText PropDiscriminator = System.Text.Json.JsonEncodedText.Encode("type");

	public override IProperty Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
	{
		reader.ValidateToken(System.Text.Json.JsonTokenType.StartObject);
		var readerSnapshot = reader;
		string? discriminator = "object";
		while (reader.Read() && reader.TokenType is System.Text.Json.JsonTokenType.PropertyName)
		{
			if (reader.TryReadProperty(options, PropDiscriminator, ref discriminator))
			{
				break;
			}

			reader.Skip();
		}

		reader = readerSnapshot;
		return discriminator switch
		{
			"aggregate_metric_double" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.AggregateMetricDoubleProperty>(options),
			"binary" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.BinaryProperty>(options),
			"boolean" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.BooleanProperty>(options),
			"byte" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.ByteNumberProperty>(options),
			"completion" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.CompletionProperty>(options),
			"constant_keyword" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.ConstantKeywordProperty>(options),
			"date_nanos" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateNanosProperty>(options),
			"date" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateProperty>(options),
			"date_range" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.DateRangeProperty>(options),
			"dense_vector" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.DenseVectorProperty>(options),
			"double" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleNumberProperty>(options),
			"double_range" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleRangeProperty>(options),
			"{dynamic_type}" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.DynamicProperty>(options),
			"alias" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.FieldAliasProperty>(options),
			"flattened" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.FlattenedProperty>(options),
			"float" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatNumberProperty>(options),
			"float_range" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatRangeProperty>(options),
			"geo_point" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoPointProperty>(options),
			"geo_shape" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoShapeProperty>(options),
			"half_float" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.HalfFloatNumberProperty>(options),
			"histogram" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.HistogramProperty>(options),
			"icu_collation_keyword" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.IcuCollationProperty>(options),
			"integer" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerNumberProperty>(options),
			"integer_range" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerRangeProperty>(options),
			"ip" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpProperty>(options),
			"ip_range" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.IpRangeProperty>(options),
			"join" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.JoinProperty>(options),
			"keyword" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.KeywordProperty>(options),
			"long" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongNumberProperty>(options),
			"long_range" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.LongRangeProperty>(options),
			"match_only_text" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.MatchOnlyTextProperty>(options),
			"murmur3" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.Murmur3HashProperty>(options),
			"nested" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.NestedProperty>(options),
			"object" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.ObjectProperty>(options),
			"passthrough" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.PassthroughObjectProperty>(options),
			"percolator" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.PercolatorProperty>(options),
			"point" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.PointProperty>(options),
			"rank_feature" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeatureProperty>(options),
			"rank_features" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturesProperty>(options),
			"scaled_float" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.ScaledFloatNumberProperty>(options),
			"search_as_you_type" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.SearchAsYouTypeProperty>(options),
			"semantic_text" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.SemanticTextProperty>(options),
			"shape" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShapeProperty>(options),
			"short" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.ShortNumberProperty>(options),
			"sparse_vector" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.SparseVectorProperty>(options),
			"text" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.TextProperty>(options),
			"token_count" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.TokenCountProperty>(options),
			"unsigned_long" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.UnsignedLongNumberProperty>(options),
			"version" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.VersionProperty>(options),
			"wildcard" => reader.ReadValue<Elastic.Clients.Elasticsearch.Serverless.Mapping.WildcardProperty>(options),
			_ => throw new System.Text.Json.JsonException($"Variant '{discriminator}' is not supported for type '{nameof(IProperty)}'.")
		};
	}

	public override void Write(System.Text.Json.Utf8JsonWriter writer, IProperty value, System.Text.Json.JsonSerializerOptions options)
	{
		switch (value.Type)
		{
			case "aggregate_metric_double":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.AggregateMetricDoubleProperty)value);
				break;
			case "binary":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.BinaryProperty)value);
				break;
			case "boolean":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.BooleanProperty)value);
				break;
			case "byte":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.ByteNumberProperty)value);
				break;
			case "completion":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.CompletionProperty)value);
				break;
			case "constant_keyword":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.ConstantKeywordProperty)value);
				break;
			case "date_nanos":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.DateNanosProperty)value);
				break;
			case "date":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.DateProperty)value);
				break;
			case "date_range":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.DateRangeProperty)value);
				break;
			case "dense_vector":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.DenseVectorProperty)value);
				break;
			case "double":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleNumberProperty)value);
				break;
			case "double_range":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.DoubleRangeProperty)value);
				break;
			case "{dynamic_type}":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.DynamicProperty)value);
				break;
			case "alias":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.FieldAliasProperty)value);
				break;
			case "flattened":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.FlattenedProperty)value);
				break;
			case "float":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatNumberProperty)value);
				break;
			case "float_range":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.FloatRangeProperty)value);
				break;
			case "geo_point":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoPointProperty)value);
				break;
			case "geo_shape":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.GeoShapeProperty)value);
				break;
			case "half_float":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.HalfFloatNumberProperty)value);
				break;
			case "histogram":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.HistogramProperty)value);
				break;
			case "icu_collation_keyword":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.IcuCollationProperty)value);
				break;
			case "integer":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerNumberProperty)value);
				break;
			case "integer_range":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.IntegerRangeProperty)value);
				break;
			case "ip":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.IpProperty)value);
				break;
			case "ip_range":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.IpRangeProperty)value);
				break;
			case "join":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.JoinProperty)value);
				break;
			case "keyword":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.KeywordProperty)value);
				break;
			case "long":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.LongNumberProperty)value);
				break;
			case "long_range":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.LongRangeProperty)value);
				break;
			case "match_only_text":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.MatchOnlyTextProperty)value);
				break;
			case "murmur3":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.Murmur3HashProperty)value);
				break;
			case "nested":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.NestedProperty)value);
				break;
			case "object":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.ObjectProperty)value);
				break;
			case "passthrough":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.PassthroughObjectProperty)value);
				break;
			case "percolator":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.PercolatorProperty)value);
				break;
			case "point":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.PointProperty)value);
				break;
			case "rank_feature":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeatureProperty)value);
				break;
			case "rank_features":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.RankFeaturesProperty)value);
				break;
			case "scaled_float":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.ScaledFloatNumberProperty)value);
				break;
			case "search_as_you_type":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.SearchAsYouTypeProperty)value);
				break;
			case "semantic_text":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.SemanticTextProperty)value);
				break;
			case "shape":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.ShapeProperty)value);
				break;
			case "short":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.ShortNumberProperty)value);
				break;
			case "sparse_vector":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.SparseVectorProperty)value);
				break;
			case "text":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.TextProperty)value);
				break;
			case "token_count":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.TokenCountProperty)value);
				break;
			case "unsigned_long":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.UnsignedLongNumberProperty)value);
				break;
			case "version":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.VersionProperty)value);
				break;
			case "wildcard":
				writer.WriteValue(options, (Elastic.Clients.Elasticsearch.Serverless.Mapping.WildcardProperty)value);
				break;
			default:
				throw new System.Text.Json.JsonException($"Variant '{value.Type}' is not supported for type '{nameof(IProperty)}'.");
		}
	}
}

[JsonConverter(typeof(PropertyInterfaceConverter))]
public partial interface IProperty
{
	public string? Type { get; }
}